#This file was generated by Claude Opus 5.5
#01/10/2026
#
# Tests for the domain history (DomainHistory in CreateDomain.jl): recording of
# create_* calls, obj_id assignment, deletion, and backward compatibility.
# Included from runtests.jl.

using FITToolbox, Test
using FITToolbox: CreateObject, DeleteObject, Brick, Sphere, CircularLoop, Material,
                  _record_delete!, _active_ids, _discretize_source, _replay!

_hist_domain() = create_domain([6.0, 8.0, 10.0], [2.0, 2.0, 2.0])

@testset "history: new domain" begin
    d = _hist_domain()
    @test isempty(d._history.steps)
    @test d._history.obj_counter == 0
    @test isempty(_active_ids(d._history))

    # internal field: hidden from tab completion, but still reachable
    @test :_history ∉ propertynames(d)
    @test :_history ∈ propertynames(d, true)
end

@testset "history: create_brick! is recorded" begin
    d = create_domain([60.0, 80.0, 100.0], [20.0, 20.0, 20.0]; units="mm")
    id = create_brick!(d, 0, 20, 40, 40, 40, 20; units="mm", σ=5.8e7,
                       name="plate", color="#B87333")
    @test id == 1
    @test length(d._history.steps) == 1

    step = only(d._history.steps)
    @test step isa CreateObject
    @test step.obj_id == 1
    @test step.name == "plate"
    @test step.object isa Brick
    # stored in metres, independent of the units used in the call
    @test all(step.object.origin  .≈ (0.0, 0.02, 0.04))
    @test all(step.object.lengths .≈ (0.04, 0.04, 0.02))
    @test step.object.material == Material(5.8e7, 1.0, 1.0, "#B87333")
end

@testset "history: create_sphere! is recorded" begin
    d = _hist_domain()
    id = create_sphere!(d, 3.0, 4.0, 5.0, 2.0; ε_r=4.0, name="ball")
    @test id == 1

    step = only(d._history.steps)
    @test step.object isa Sphere
    @test step.object.center == (3.0, 4.0, 5.0)
    @test step.object.radius == 2.0
    @test step.object.material == Material(0.0, 4.0, 1.0)   # color defaults to nothing
    @test step.name == "ball"
end

@testset "history: obj_id counts upwards across shape types" begin
    d = _hist_domain()
    @test create_brick!(d, 0, 0, 0, 2, 2, 2)    == 1
    @test create_sphere!(d, 3, 4, 5, 2)         == 2
    @test create_brick!(d, 2, 2, 2, 2, 2, 2)    == 3
    @test [s.obj_id for s in d._history.steps]  == [1, 2, 3]
    @test _active_ids(d._history)               == [1, 2, 3]
    @test d._history.obj_counter                == 3
end

@testset "history: failed calls are not recorded" begin
    d = _hist_domain()
    create_brick!(d, 0, 0, 0, 2, 2, 2)

    @test_throws ArgumentError create_brick!(d, 0, 0, 0, 100, 2, 2)    # beyond the domain
    @test_throws ArgumentError create_brick!(d, 0, 0, 0, 0.5, 2, 2)    # thinner than one cell
    @test_throws ArgumentError create_sphere!(d, 3, 4, 5, 0.0)         # zero radius
    @test_throws ArgumentError create_sphere!(d, 30, 4, 5, 1.0)        # centre outside

    @test length(d._history.steps) == 1
    @test d._history.obj_counter   == 1
    @test create_brick!(d, 2, 2, 2, 2, 2, 2) == 2    # no ids were used up by the failures
end

@testset "history: delete" begin
    d = _hist_domain()
    create_brick!(d, 0, 0, 0, 2, 2, 2)
    create_sphere!(d, 3, 4, 5, 2)

    _record_delete!(d, 1)
    @test d._history.steps[end] == DeleteObject(1)
    @test length(d._history.steps) == 3            # a delete is a step of its own
    @test _active_ids(d._history) == [2]
    @test d._history.obj_counter == 2              # deleting does not hand out an id

    @test_throws ArgumentError _record_delete!(d, 1)    # already deleted
    @test_throws ArgumentError _record_delete!(d, 99)   # never existed
    @test length(d._history.steps) == 3

    # a deleted id is never handed out again
    @test create_brick!(d, 0, 0, 0, 2, 2, 2) == 3
    @test _active_ids(d._history) == [2, 3]
end

@testset "history: each domain has its own" begin
    a = _hist_domain()
    b = _hist_domain()
    create_brick!(a, 0, 0, 0, 2, 2, 2)
    @test length(a._history.steps) == 1
    @test isempty(b._history.steps)
    @test create_sphere!(b, 3, 4, 5, 2) == 1       # ids are per domain

    c = deepcopy(a)                                # a copy gets an independent history
    create_brick!(c, 2, 2, 2, 2, 2, 2)
    @test length(c._history.steps) == 2
    @test length(a._history.steps) == 1
end

@testset "history: FITDomain constructor without history (backward compatibility)" begin
    d = _hist_domain()
    e = FITDomain(d.nodes_u, d.nodes_v, d.nodes_w,
                  d.edges_u, d.edges_v, d.edges_w,
                  d.dual_edges_u, d.dual_edges_v, d.dual_edges_w,
                  d.edges_u_center, d.edges_v_center, d.edges_w_center,
                  d.primal_facets_u, d.primal_facets_v, d.primal_facets_w,
                  d.dual_facets_u, d.dual_facets_v, d.dual_facets_w,
                  d.σ, d.ε_r, d.μ_r,
                  copy(d.material))
    @test isempty(e._history.steps)
    @test create_brick!(e, 0, 0, 0, 2, 2, 2) == 1
end

@testset "history: create_circular_loop_source! is recorded" begin
    # same grid and loop as in sources.jl: off-centre, no warnings
    wire_domain() = create_domain([20.0, 30.0, 30.0], [1.0, 0.5, 0.5])
    d = wire_domain()
    id = create_circular_loop_source!(d, 8000.0, 10300.0, 15200.0, 14900.0, DirX();
                                      units="mm", name="coil")

    # returns the obj_id, like create_brick!; the vector comes from get_source
    @test id == 1
    J = get_source(d, id)
    @test J isa Vector{Float64}
    @test length(J) == 3*d.Np

    step = only(d._history.steps)
    @test step isa CreateObject
    @test step.obj_id == 1
    @test step.name == "coil"
    @test step.object isa CircularLoop
    @test all(step.object.center .≈ (10.3, 15.2, 14.9))     # stored in metres
    @test step.object.radius ≈ 8.0
    @test step.object.normal == DirX()
    @test step.object.current == 1.0                       # default: 1 A, as before
    @test _discretize_source(d, step.object) == J           # the record reproduces J

    # current scales the vector
    d2 = wire_domain()
    J2 = get_source(d2, create_circular_loop_source!(d2, 8.0, 10.3, 15.2, 14.9, DirX(); current=1000.0))
    @test J2 == 1000.0 .* J
    @test only(d2._history.steps).object.current == 1000.0

    # solids and sources share one id sequence
    d3 = wire_domain()
    @test create_brick!(d3, 0, 0, 0, 2, 2, 2) == 1
    @test create_circular_loop_source!(d3, 8.0, 10.3, 15.2, 14.9, DirX()) == 2
    @test create_sphere!(d3, 10, 15, 15, 2) == 3

    # failed calls are not recorded
    @test_throws ArgumentError create_circular_loop_source!(d, 8.0, 10.3, 15.2, 14.9, DirY())  # u + R = 18.3 > nodes_u[end-2]
    @test_throws ArgumentError create_circular_loop_source!(d, 8.0, 10.3, 15.2, 29.5, DirZ())  # plane beyond nodes_w[end-2]
    @test_throws ArgumentError create_circular_loop_source!(d, 8.0, 19.5, 15.2, 14.9, DirX())  # plane beyond nodes_u[end-2]
    @test_throws ArgumentError create_circular_loop_source!(d, 8.0, 10.3, 25.0, 14.9, DirX())  # v + R beyond the domain
    @test length(d._history.steps) == 1
end

@testset "history: replay" begin
    mk() = create_domain([6.0, 8.0, 10.0], [0.5, 0.5, 0.5]; σ=0.1, ε_r=2.0)
    a = mk()
    create_brick!(a, 0, 0, 0, 4, 4, 4; σ=5.0)
    create_sphere!(a, 3, 4, 5, 2.5; ε_r=7.0, μ_r=3.0)
    create_circular_loop_source!(a, 1.0, 3.0, 4.0, 5.0, DirX())
    create_brick!(a, 2, 2, 2, 2, 2, 6; μ_r=9.0)       # overlaps brick 1 and the sphere

    # replay reproduces the material exactly, including overlaps and background
    ref = copy(a.material)
    a.material .= -1.0
    @test_logs _replay!(a)
    @test a.material == ref

    # deleting the sphere gives the same result as never creating it
    _record_delete!(a, 2)
    @test_logs _replay!(a)
    b = mk()
    create_brick!(b, 0, 0, 0, 4, 4, 4; σ=5.0)
    create_brick!(b, 2, 2, 2, 2, 2, 6; μ_r=9.0)
    @test a.material == b.material
end

@testset "history: remove_object!" begin
    mk() = create_domain([6.0, 8.0, 10.0], [0.5, 0.5, 0.5]; σ=0.1, ε_r=2.0)
    a = mk()
    create_brick!(a, 0, 0, 0, 4, 4, 4; σ=5.0)
    id_sphere = create_sphere!(a, 3, 4, 5, 2.5; ε_r=7.0, μ_r=3.0)
    create_brick!(a, 2, 2, 2, 2, 2, 6; μ_r=9.0)       # overlaps brick 1 and the sphere

    # removing the sphere: material as if it had never been created
    @test (@test_logs remove_object!(a, id_sphere)) === nothing
    b = mk()
    create_brick!(b, 0, 0, 0, 4, 4, 4; σ=5.0)
    create_brick!(b, 2, 2, 2, 2, 2, 6; μ_r=9.0)
    @test a.material == b.material
    @test a._history.steps[end] == DeleteObject(id_sphere)
    @test _active_ids(a._history) == [1, 3]

    # invalid ids throw before anything changes: no step recorded, material untouched
    before, nsteps = copy(a.material), length(a._history.steps)
    @test_throws ArgumentError remove_object!(a, id_sphere)   # already removed
    @test_throws ArgumentError remove_object!(a, 99)          # never existed
    @test length(a._history.steps) == nsteps
    @test a.material == before

    # removing all solids restores the background
    @test_logs remove_object!(a, 1)
    @test_logs remove_object!(a, 3)
    @test all(a.material[:, :, :, 1] .== 0.1)
    @test all(a.material[:, :, :, 2] .== 2.0)
    @test all(a.material[:, :, :, 3] .== 1.0)
    @test isempty(_active_ids(a._history))

    # removing a source keeps the material unchanged
    c = mk()
    create_brick!(c, 0, 0, 0, 4, 4, 4; σ=5.0)
    id_loop = create_circular_loop_source!(c, 1.0, 3.0, 4.0, 5.0, DirX())
    before  = copy(c.material)
    @test_logs remove_object!(c, id_loop)
    @test c.material == before
    @test _active_ids(c._history) == [1]
end

@testset "history: list_objects" begin
    d = create_domain([20.0, 30.0, 30.0], [1.0, 0.5, 0.5])
    @test isempty(list_objects(d))
    @test repr(MIME"text/plain"(), list_objects(d)) == "0 objects"

    create_brick!(d, 0, 0, 0, 4, 4, 4; σ=5.8e7, name="plate", color="#B87333")
    create_sphere!(d, 10, 15, 15, 2; ε_r=4.0, name="shell")
    create_sphere!(d, 10, 15, 15, 1; ε_r=9.0)                          # no name
    create_circular_loop_source!(d, 8.0, 10.3, 15.2, 14.9, DirX(); name="coil", current=1000.0)
    @test_logs remove_object!(d, 2)

    # data: existing objects in creation order, the removed one left out
    l = list_objects(d)
    @test l isa AbstractVector
    @test length(l) == 3
    @test [e.obj_id for e in l]       == [1, 3, 4]
    @test [e.name for e in l]         == ["plate", "obj3", "coil"]
    @test [e.object isa T for (e, T) in zip(l, (Brick, Sphere, CircularLoop))] == [true, true, true]
    @test only(filter(e -> e.name == "coil", l)).obj_id == 4
    @test l[1].object.material.color == "#B87333"

    # a snapshot: later changes to the domain do not alter an earlier list
    create_brick!(d, 2, 2, 2, 2, 2, 2)
    @test length(l) == 3
    @test length(list_objects(d)) == 4

    # table: summary line, header, one row per object
    lines = split(repr(MIME"text/plain"(), l), '\n')
    @test lines[1] == "3 objects:"
    @test length(lines) == 5
    @test occursin("obj_id", lines[2]) && occursin("geometry (m)", lines[2])
    @test occursin(r"^\s+1\s+Brick\s+plate\s", lines[3])
    @test occursin(r"^\s+3\s+Sphere\s+obj3\s", lines[4])               # unnamed object gets "obj<id>"
    @test occursin(r"^\s+4\s+CircularLoop\s+coil\s", lines[5])
    @test occursin("color=#B87333", lines[3])
    @test occursin("normal=DirX", lines[5]) && occursin("I=1000.0 A", lines[5])
    @test !any(endswith(' '), lines)                                    # no trailing spaces

    # singular for one object
    e = create_domain([6.0, 8.0, 10.0], [2.0, 2.0, 2.0])
    create_brick!(e, 0, 0, 0, 2, 2, 2)
    @test startswith(repr(MIME"text/plain"(), list_objects(e)), "1 object:")
end

@testset "history: list_objects rounds float noise" begin
    # nodes from a running sum of 0.01: nodes_v[end] = 1.0000000000000007, not 1.0
    d = create_domain([100, 100, 100], [1, 1, 1]; units="cm")
    c = d.nodes_v[end] / 2 * 100                                     # 50.000000000000036 cm
    create_sphere!(d, 65, c, c, 20; units="cm", σ=5.8e7, name="ball")
    create_circular_loop_source!(d, 10, 30, c, c, DirX(); units="cm", current=1 + 1im, name="ac")
    @test only(e for e in list_objects(d) if e.name == "ball").object.center[2] != 0.5   # stored as is

    table = repr(MIME"text/plain"(), list_objects(d))
    @test occursin("center=(0.65, 0.5, 0.5) radius=0.2", table)     # shown rounded
    @test occursin("σ=5.8e7 ε_r=1.0 μ_r=1.0", table)
    @test occursin("I=1.0 + 1.0im A", table)
    @test !occursin("00000000", table)
end

@testset "history: material colors" begin
    @test Material(0, 1, 1).color === nothing
    @test Material(0, 1, 1, "Red").color == "red"                 # names stored in lowercase
    @test Material(0, 1, 1, "#b87333").color == "#b87333"         # hex codes unchanged
    @test FITToolbox._color_hex("copper") == "#B87333"
    for bad in ("redd", "#B8733", "red ", "rgb(1,0,0)")
        @test_throws ArgumentError Material(0, 1, 1, bad)
    end

    d = create_domain([6.0, 8.0, 10.0], [2.0, 2.0, 2.0])
    @test_throws ArgumentError create_brick!(d, 0, 0, 0, 2, 2, 2; color="redd")
    @test isempty(d._history.steps)                               # not recorded
end

@testset "history: rebuild warns only about values written directly" begin
    mk() = (d = create_domain([6.0, 8.0, 10.0], [0.5, 0.5, 0.5]);
            create_brick!(d, 0, 0, 0, 4, 4, 4; σ=5.0);
            create_brick!(d, 2, 2, 2, 2, 2, 6; μ_r=9.0); d)

    # built only with create_*: no warning
    d = mk()
    @test_logs remove_object!(d, 2)
    @test_logs undo!(d)

    # a value written into domain.material: warned about and discarded, every time
    for op! in (d -> remove_object!(d, 2), undo!)
        d = mk()
        d.material[end, end, end, 2] = 42.0
        @test_logs (:warn, r"Rebuilding") op!(d)
        @test d.material[end, end, end, 2] == 1.0
    end

    # the check is silent: a clipped sphere warns once per rebuild, when the rebuild
    # applies it, not a second time from the check before
    d = mk()
    @test_logs (:warn, r"clipped") create_sphere!(d, 5.5, 4, 5, 1.0)
    @test_logs (:warn, r"clipped") remove_object!(d, 1)
    @test_logs (:warn, r"clipped") undo!(d)
end

@testset "history: undo!" begin
    mk() = create_domain([6.0, 8.0, 10.0], [0.5, 0.5, 0.5]; σ=0.1, ε_r=2.0)
    a = mk()
    @test_throws ArgumentError undo!(a)                     # empty history

    create_brick!(a, 0, 0, 0, 4, 4, 4; σ=5.0)
    after_brick = copy(a.material)
    create_sphere!(a, 3, 4, 5, 2.5; ε_r=7.0, μ_r=3.0)
    after_sphere = copy(a.material)

    # undoing a create removes the object again
    @test (@test_logs undo!(a)) === nothing
    @test a.material == after_brick
    @test _active_ids(a._history) == [1]
    @test length(a._history.steps) == 1

    # ids are not handed out again: the next object gets 3, not 2
    @test create_sphere!(a, 3, 4, 5, 2.5; ε_r=7.0, μ_r=3.0) == 3
    @test a.material == after_sphere

    # undoing a delete brings the object back
    @test_logs remove_object!(a, 3)
    @test a.material == after_brick
    @test_logs undo!(a)
    @test a.material == after_sphere
    @test _active_ids(a._history) == [1, 3]

    # undoing a source leaves the material unchanged
    create_circular_loop_source!(a, 1.0, 3.0, 4.0, 5.0, DirX())
    @test_logs undo!(a)
    @test a.material == after_sphere
    @test _active_ids(a._history) == [1, 3]

    # undo everything: back to the background, then nothing left to undo
    while !isempty(a._history.steps)
        @test_logs undo!(a)
    end
    @test a.material == mk().material
    @test_throws ArgumentError undo!(a)
    @test a._history.obj_counter == 4                       # the counter never goes back
end

@testset "history: change_resolution" begin
    build!(d) = (create_brick!(d, 0, 0, 0, 4, 4, 4; σ=5.0, name="plate");
                 create_sphere!(d, 3, 4, 5, 2.5; ε_r=7.0, μ_r=3.0);
                 create_circular_loop_source!(d, 1.0, 3.0, 4.0, 5.0, DirX());
                 create_brick!(d, 2, 2, 2, 2, 2, 6; μ_r=9.0); d)

    coarse = build!(create_domain([6.0, 8.0, 10.0], [0.5, 0.5, 0.5]; σ=0.1, ε_r=2.0))
    @test_logs remove_object!(coarse, 4)
    hist_before, mat_before = copy(coarse._history.steps), copy(coarse.material)

    # uniform: same result as building the model directly at the new resolution
    fine = @test_logs change_resolution(coarse, 0.25)                # clean domain: no warning
    direct = build!(create_domain([6.0, 8.0, 10.0], [0.25, 0.25, 0.25]; σ=0.1, ε_r=2.0))
    @test_logs remove_object!(direct, 4)
    @test (fine.Nu, fine.Nv, fine.Nw) == (25, 33, 41)
    @test fine.material == direct.material
    fine_material = copy(fine.material)
    @test (fine.σ, fine.ε_r, fine.μ_r) == (0.1, 2.0, 1.0)
    @test fine._history.steps == hist_before
    @test [e.obj_id for e in list_objects(fine)] == [1, 2, 3]
    @test create_brick!(fine, 0, 0, 0, 1, 1, 1) == 5

    # the original is untouched and independent
    @test coarse._history.steps == hist_before
    @test coarse.material == mat_before
    @test_logs undo!(fine)
    @test coarse._history.steps == hist_before

    # per-direction values and units
    mm = @test_logs change_resolution(coarse, (500, 250, 1000); units="mm")
    @test (mm.Nu, mm.Nv, mm.Nw) == (13, 33, 11)

    # non-uniform edges: same result as create_domain with these edges
    eu = [1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0]                     # 6 m
    ev = [2.0, 1.0, 0.5, 0.5, 0.5, 0.5, 1.0, 2.0]                     # 8 m
    ew = fill(0.5, 20)                                                # 10 m
    graded = @test_logs change_resolution(coarse, eu, ev, ew)
    direct = build!(create_domain(eu, ev, ew; σ=0.1, ε_r=2.0))
    @test_logs remove_object!(direct, 4)
    @test graded.edges_u == eu
    @test graded.material == direct.material
    mmg = @test_logs change_resolution(coarse, 1000 .* eu, 1000 .* ev, 1000 .* ew; units="mm")
    @test mmg.material == graded.material
    @test eu == [1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0]              # input not modified
    @test_throws ArgumentError change_resolution(coarse, eu[1:end-1], ev, ew)   # 5 m instead of 6 m

    # manually set material values: warned about, not carried over
    coarse.material[1, 1, 1, 2] = 42.0
    fine2 = @test_logs (:warn, r"not carried over") change_resolution(coarse, 0.25)
    @test fine2.material == fine_material
    @test coarse.material[1, 1, 1, 2] == 42.0                          # original untouched

    # an object that no longer fits the grid: error, original unchanged
    t = create_domain([6.0, 8.0, 10.0], [0.5, 0.5, 0.5])
    create_brick!(t, 0, 0, 0, 0.5, 4, 4)
    @test_throws ArgumentError change_resolution(t, 2.0)
    @test length(t._history.steps) == 1
    @test_throws ArgumentError change_resolution(t, (1.0, 1.0))
end

@testset "history: get_source" begin
    mk() = create_domain([20.0, 30.0, 30.0], [1.0, 0.5, 0.5])
    d = mk()
    create_brick!(d, 0, 0, 0, 4, 4, 4; σ=5.8e7, name="plate")
    @test create_circular_loop_source!(d, 8.0, 10.3, 15.2, 14.9, DirX(); name="coil", current=1000.0) == 2
    @test create_circular_loop_source!(d, 5.0, 6.0, 15.0, 15.0, DirX(); name="pickup", current=-200.0) == 3

    # reference: each loop alone in an empty domain of the same grid
    alone(args...; kw...) = (e = mk(); get_source(e, create_circular_loop_source!(e, args...; kw...)))
    J1 = alone(8.0, 10.3, 15.2, 14.9, DirX(); current=1000.0)
    J2 = alone(5.0, 6.0, 15.0, 15.0, DirX(); current=-200.0)

    # one source, by name or id: the same vector as the loop alone
    @test get_source(d, "coil")   == J1
    @test get_source(d, 2)        == J1
    @test get_source(d, "pickup") == J2
    @test length(get_source(d, "coil")) == 3 * d.Np

    # each source on its own, not mixed with the others
    @test get_source(d, "coil") != get_source(d, "coil") .+ get_source(d, "pickup")

    # solids and unknown objects are rejected
    @test_throws ArgumentError get_source(d, "plate")
    @test_throws ArgumentError get_source(d, 1)
    @test_throws ArgumentError get_source(d, "nothing")
    @test_throws ArgumentError get_source(d, 99)

    # removed sources are gone, undo brings them back
    @test_logs remove_object!(d, "pickup")
    @test_throws ArgumentError get_source(d, "pickup")
    @test get_source(d, "coil") == J1                                  # the other source is untouched
    @test_logs undo!(d)
    @test get_source(d, "pickup") == J2

    # after change_resolution: same as creating the loop on the new grid
    fine = change_resolution(d, (0.5, 0.25, 0.25))
    direct = create_domain([20.0, 30.0, 30.0], [0.5, 0.25, 0.25])
    @test get_source(fine, "coil") ==
          get_source(direct, create_circular_loop_source!(direct, 8.0, 10.3, 15.2, 14.9, DirX(); current=1000.0))
    @test length(get_source(fine, "coil")) == 3 * fine.Np
    @test get_source(d, "coil") == J1                                  # the original keeps its grid
end


@testset "history: names" begin
    d = create_domain([20.0, 30.0, 30.0], [1.0, 0.5, 0.5])

    # default names "obj<id>", user names kept
    @test create_brick!(d, 0, 0, 0, 4, 4, 4; σ=5.8e7) == 1
    @test create_sphere!(d, 10, 15, 15, 2; ε_r=4.0, name="head") == 2
    @test create_circular_loop_source!(d, 8.0, 10.3, 15.2, 14.9, DirX(); name="coil", current=1000.0) == 3
    @test create_circular_loop_source!(d, 5.0, 6.0, 15.0, 15.0, DirX()) == 4
    alone(args...; kw...) = (e = create_domain([20.0, 30.0, 30.0], [1.0, 0.5, 0.5]);
                             get_source(e, create_circular_loop_source!(e, args...; kw...)))
    J1 = alone(8.0, 10.3, 15.2, 14.9, DirX(); current=1000.0)
    J2 = alone(5.0, 6.0, 15.0, 15.0, DirX())
    @test [e.name for e in list_objects(d)] == ["obj1", "head", "coil", "obj4"]

    # names are unique; "obj<number>" is reserved; a rejected name changes nothing
    before = copy(d.material)
    @test_throws ArgumentError create_sphere!(d, 10, 15, 15, 3; ε_r=9.0, name="head")
    @test_throws ArgumentError create_brick!(d, 0, 0, 0, 2, 2, 2; name="obj7")
    @test_throws ArgumentError create_circular_loop_source!(d, 5.0, 6.0, 15.0, 15.0, DirX(); name="coil")
    @test d.material == before
    @test length(d._history.steps) == 4
    @test create_brick!(d, 0, 0, 0, 2, 2, 2) == 5                 # no id used up by the failures
    @test list_objects(d)[end].name == "obj5"

    # source by name or id
    @test get_source(d, "coil") == J1
    @test get_source(d, 3)      == J1
    @test get_source(d, "obj4") == J2
    @test_throws ArgumentError get_source(d, "head")              # a sphere, not a source
    @test_throws ArgumentError get_source(d, 2)
    @test_throws ArgumentError get_source(d, "nothing")           # no such object
    @test_throws ArgumentError get_source(d, 99)

    # remove by name; the name becomes free again
    @test_logs remove_object!(d, "head")
    @test "head" ∉ [e.name for e in list_objects(d)]
    @test_throws ArgumentError remove_object!(d, "head")
    @test create_sphere!(d, 10, 15, 15, 1; ε_r=2.0, name="head") == 6

    # undo steps back through states that were valid, so names stay unique
    @test_logs undo!(d)                    # undoes creating the new "head"
    @test_logs undo!(d)                    # undoes the removal: old "head" back
    @test only(e for e in list_objects(d) if e.name == "head").obj_id == 2
end

@testset "history: complex current" begin
    mk(res) = create_domain([20.0, 30.0, 30.0], res)
    loop!(d, I, name) = create_circular_loop_source!(d, 8.0, 10.3, 15.2, 14.9, DirX();
                                                     current=I, name=name)
    d = mk([1.0, 0.5, 0.5])
    create_brick!(d, 0, 0, 0, 4, 4, 4; σ=5.8e7, name="plate")
    loop!(d, 100.0 + 50.0im, "ac")

    # change_resolution: the phasor is kept, same as creating it on the new grid
    fine   = change_resolution(d, (0.5, 0.25, 0.25))
    direct = mk([0.5, 0.25, 0.25])
    @test get_source(fine, "ac") == get_source(direct, loop!(direct, 100.0 + 50.0im, "ac"))
    @test eltype(get_source(fine, "ac")) == ComplexF64

    # remove and undo bring back the same complex source
    Jc = get_source(d, "ac")
    @test_logs remove_object!(d, "ac")
    @test_throws ArgumentError get_source(d, "ac")
    @test_logs undo!(d)
    @test get_source(d, "ac") == Jc
end
