#This file was generated by Opus 5.0
#11/09/2026
#
# Tests for get_index_entity (GetIndexOfEntity.jl) and its inverse
# get_position_of_index (GetPositionOfIndex.jl). Included from runtests.jl.

using FITToolbox, Test

# Graded and different in every direction, so u, v and w cannot be confused.
#   nodes_u = 0, 1, 3, 3.5, 6.5          centres_u = 0.5, 2, 3.25, 5
#   nodes_v = 0, 2, 3, 4.5               centres_v = 1, 2.5, 3.75
#   nodes_w = 0, 0.5, 1.5, 2.5, 4.5, 5.25   centres_w = 0.25, 1, 2, 3.5, 4.875
const _IX = create_domain([1.0, 2.0, 0.5, 3.0], [2.0, 1.0, 1.5],
                          [0.5, 1.0, 1.0, 2.0, 0.75]; units = "m")

_ix_idx(d, i, j, k) = i + (j-1)*d.Nu + (k-1)*d.Nu*d.Nv

# For component n (1 = u, 2 = v, 3 = w): true along the axes where the entity sits
# at edge centres (N-1 positions) rather than on nodes (N positions).
_ix_centred(::Union{PrimalEdge, DualFacet},   n) = (n == 1, n == 2, n == 3)
_ix_centred(::Union{DualEdge, PrimalFacet},   n) = (n != 1, n != 2, n != 3)
_ix_centred(::Union{PrimalNode, DualVolume},  n) = (false, false, false)
_ix_centred(::Union{DualNode, PrimalVolume},  n) = (true, true, true)


@testset "indexing" begin

d = _IX

@testset "positions of individual entities" begin
    @test get_position_of_index(d, PrimalNode(),  DirX(), 2, 3, 4) == (1.0, 3.0,  2.5)
    @test get_position_of_index(d, DualNode(),    DirX(), 2, 3, 4) == (2.0, 3.75, 3.5)
    @test get_position_of_index(d, PrimalEdge(),  DirX(), 2, 3, 4) == (2.0, 3.0,  2.5)   # u-edge: centre in u
    @test get_position_of_index(d, PrimalEdge(),  DirZ(), 2, 3, 4) == (1.0, 3.0,  3.5)   # w-edge: centre in w
    @test get_position_of_index(d, DualFacet(),   DirY(), 2, 3, 4) == (1.0, 3.75, 2.5)   # pierced by a v-edge
    @test get_position_of_index(d, DualEdge(),    DirX(), 2, 3, 4) == (1.0, 3.75, 3.5)   # through a u-facet
    @test get_position_of_index(d, PrimalFacet(), DirY(), 2, 3, 4) == (2.0, 3.0,  3.5)   # centre of a v-facet

    # the flat form also returns the component
    p = _ix_idx(d, 2, 3, 4)
    @test get_position_of_index(d, PrimalEdge(), p + 2 * d.Np) == (1.0, 3.0, 3.5, DirZ())
    @test get_position_of_index(d, PrimalNode(), p)            == (1.0, 3.0, 2.5, DirX())

    @test get_position_of_index(d, PrimalNode(), DirX(), 2, 3, 4; units = "mm") == (1000.0, 3000.0, 2500.0)
end

@testset "indices of individual entities" begin
    p = _ix_idx(d, 2, 3, 4)
    @test get_index_entity(d, PrimalNode(), 1.0, 3.0, 2.5)                 == p
    @test get_index_entity(d, DualNode(),   2.0, 3.75, 3.5)                == p
    @test get_index_entity(d, PrimalEdge(), DirZ(), 1.0, 3.0, 3.5)         == p + 2 * d.Np
    @test get_index_entity(d, DualEdge(),   DirY(), 2.0, 3.0, 3.5)         == p + d.Np
    @test get_index_entity(d, PrimalNode(), 1000.0, 3000.0, 2500.0; units = "mm") == p

    # single-component entities ignore the normal
    for normal in (DirX(), DirY(), DirZ())
        @test get_index_entity(d, PrimalNode(),   normal, 1.0, 3.0,  2.5) == p
        @test get_index_entity(d, PrimalVolume(), normal, 2.0, 3.75, 3.5) == p
    end
end

@testset "get_index_entity and get_position_of_index are inverse" begin
    # every entity that exists, for all eight entity types and all components
    for entity in (PrimalEdge(), DualFacet(), DualEdge(), PrimalFacet())
        mismatches = 0
        for (n, normal) in enumerate((DirX(), DirY(), DirZ()))
            cu, cv, cw = _ix_centred(entity, n)
            for k in 1:d.Nw-cw, j in 1:d.Nv-cv, i in 1:d.Nu-cu
                p = _ix_idx(d, i, j, k) + (n-1) * d.Np
                x, y, z = get_position_of_index(d, entity, normal, i, j, k)
                get_index_entity(d, entity, normal, x, y, z) == p  || (mismatches += 1)
                get_position_of_index(d, entity, p) == (x, y, z, normal) || (mismatches += 1)
            end
        end
        @test mismatches == 0
    end

    for entity in (PrimalNode(), DualVolume(), DualNode(), PrimalVolume())
        mismatches = 0
        cu, cv, cw = _ix_centred(entity, 1)
        for k in 1:d.Nw-cw, j in 1:d.Nv-cv, i in 1:d.Nu-cu
            p = _ix_idx(d, i, j, k)
            x, y, z = get_position_of_index(d, entity, DirX(), i, j, k)
            get_index_entity(d, entity, x, y, z) == p || (mismatches += 1)
            get_position_of_index(d, entity, p) == (x, y, z, DirX()) || (mismatches += 1)
        end
        @test mismatches == 0
    end
end

@testset "get_index_entity snaps to the nearest entity" begin
    p = _ix_idx(d, 2, 3, 4)
    # 0.2 m away from node (1, 3, 2.5): found, with a warning
    @test (@test_logs (:warn, r"tolerance") get_index_entity(d, PrimalNode(), 1.2, 3.0, 2.5)) == p
    # same request with a looser tolerance: silent
    @test (@test_logs get_index_entity(d, PrimalNode(), 1.2, 3.0, 2.5; atol = 0.5)) == p
    # outside the domain: clamped to the boundary node, with a warning
    @test (@test_logs (:warn, r"tolerance") get_index_entity(d, PrimalNode(), -4.0, 3.0, 2.5)) ==
          _ix_idx(d, 1, 3, 4)
end

@testset "get_position_of_index rejects indices without an entity" begin
    @test_throws BoundsError get_position_of_index(d, PrimalNode(), DirX(), 0, 1, 1)
    @test_throws BoundsError get_position_of_index(d, PrimalNode(), DirX(), 1, d.Nv + 1, 1)
    @test_throws BoundsError get_position_of_index(d, PrimalNode(), d.Np + 1)
    @test_throws BoundsError get_position_of_index(d, PrimalEdge(), 0)
    @test_throws BoundsError get_position_of_index(d, PrimalEdge(), 3 * d.Np + 1)
    # dead entities: a u-edge starting on the last node, a cell beyond the last node
    @test_throws BoundsError get_position_of_index(d, PrimalEdge(), DirX(), d.Nu, 1, 1)
    @test_throws BoundsError get_position_of_index(d, DualNode(), _ix_idx(d, d.Nu, 1, 1))
end

end
