#This file was generated by Opus 5.0
#11/09/2026
#
# Tests for interpolate on edge and facet quantities (InterpolateDualEdgePrimalFacet.jl,
# InterpolatePrimalEdgeDualFacet.jl). Included from runtests.jl.
#
# A linear field integrated over its entities must be reproduced exactly at any
# point, since trilinear interpolation reproduces linear functions on any
# rectilinear grid. Dead slots are filled with NaN, so a stencil that reaches one
# fails loudly instead of silently reading garbage.

using FITToolbox, Test

# Same graded grid as indexing.jl.
#   centres_u = 0.5 … 5,   centres_v = 1 … 3.75,   centres_w = 0.25 … 4.875
const _IP = create_domain([1.0, 2.0, 0.5, 3.0], [2.0, 1.0, 1.5],
                          [0.5, 1.0, 1.0, 2.0, 0.75]; units = "m")

# one linear function per component, all different
const _IP_LINEAR = ((x, y, z) -> 2x + 3y - z + 1,
                    (x, y, z) -> -x + y + 4z,
                    (x, y, z) -> 5x - 2y + z)

# For each component: where the entities sit, and what their value is integrated over.
_ip_layout(d, ::PrimalEdge) = (
    ((d.edges_u_center, d.nodes_v, d.nodes_w), (i, j, k) -> d.edges_u[i]),
    ((d.nodes_u, d.edges_v_center, d.nodes_w), (i, j, k) -> d.edges_v[j]),
    ((d.nodes_u, d.nodes_v, d.edges_w_center), (i, j, k) -> d.edges_w[k]))
_ip_layout(d, ::DualFacet) = (
    ((d.edges_u_center, d.nodes_v, d.nodes_w), (i, j, k) -> d.dual_facets_u[j, k]),
    ((d.nodes_u, d.edges_v_center, d.nodes_w), (i, j, k) -> d.dual_facets_v[i, k]),
    ((d.nodes_u, d.nodes_v, d.edges_w_center), (i, j, k) -> d.dual_facets_w[i, j]))
_ip_layout(d, ::DualEdge) = (
    ((d.nodes_u, d.edges_v_center, d.edges_w_center), (i, j, k) -> d.dual_edges_u[i]),
    ((d.edges_u_center, d.nodes_v, d.edges_w_center), (i, j, k) -> d.dual_edges_v[j]),
    ((d.edges_u_center, d.edges_v_center, d.nodes_w), (i, j, k) -> d.dual_edges_w[k]))
_ip_layout(d, ::PrimalFacet) = (
    ((d.nodes_u, d.edges_v_center, d.edges_w_center), (i, j, k) -> d.primal_facets_u[j, k]),
    ((d.edges_u_center, d.nodes_v, d.edges_w_center), (i, j, k) -> d.primal_facets_v[i, k]),
    ((d.edges_u_center, d.edges_v_center, d.nodes_w), (i, j, k) -> d.primal_facets_w[i, j]))

"""FIT vector of the linear field on `entity`: each value integrated, NaN on dead slots."""
function _ip_integrated_field(d, entity)
    v = fill(NaN, 3 * d.Np)
    for (c, ((X, Y, Z), measure)) in enumerate(_ip_layout(d, entity))
        for k in eachindex(Z), j in eachindex(Y), i in eachindex(X)
            p = (c-1) * d.Np + i + (j-1)*d.Nu + (k-1)*d.Nu*d.Nv
            v[p] = _IP_LINEAR[c](X[i], Y[j], Z[k]) * measure(i, j, k)
        end
    end
    return v
end


@testset "edge and facet interpolation" begin

d = _IP
entities = (PrimalEdge(), DualFacet(), DualEdge(), PrimalFacet())

@testset "reproduces a linear field: $(nameof(typeof(entity)))" for entity in entities
    v = _ip_integrated_field(d, entity)

    # between entities, on a node, and close to the outermost centres
    for (x, y, z) in ((0.7, 1.3, 0.4), (2.9, 2.6, 2.2), (4.9, 3.7, 4.8), (3.0, 2.0, 1.5))
        @test collect(interpolate(d, entity, v, x, y, z)) ≈
              [f(x, y, z) for f in _IP_LINEAR] atol = 1e-12
    end

    # units rescale the query position only
    @test collect(interpolate(d, entity, v, 2900.0, 2600.0, 2200.0; units = "mm")) ≈
          collect(interpolate(d, entity, v, 2.9, 2.6, 2.2)) rtol = 1e-12
end

@testset "outside the domain: NaN with a warning" begin
    v = zeros(3 * d.Np)
    for entity in entities
        got = @test_logs (:warn, r"outside of the domain") interpolate(d, entity, v, -1.0, 2.0, 2.0)
        @test length(got) == 3
        @test all(isnan, got)
    end
end

end
