#This file was generated by Opus 5.0
#11/09/2026
#
# Tests for the dual-facet-averaged material matrices M_ε and M_σ.
# Included from runtests.jl.
#
# Every grid here is graded and non-cubic, so a boundary cell never has the same
# width as its neighbour and a stride error between u, v and w cannot cancel.
# Material values are deterministic but non-uniform (no Random dependency), and
# they reach all the way to the domain boundary, which is where the averaging
# used to go wrong.

using FITToolbox, Test, LinearAlgebra, SparseArrays

const _MM = FITToolbox._get_dual_facet_averaged_material
const _ε₀ = FITToolbox.ε₀

# Nu, Nv, Nw = 5, 4, 6
const _MM_GRID = create_domain([1.0, 2.0, 0.5, 3.0], [2.0, 1.0, 1.5],
                               [0.5, 1.0, 1.0, 2.0, 0.75]; units = "m")

_mm_idx(dom, i, j, k) = i + (j-1)*dom.Nu + (k-1)*dom.Nu*dom.Nv

"""Deterministic, non-uniform cell values in [1, 5)."""
_mm_field(dom, a, b, c) =
    [1 + 4*mod(a*i + b*j + c*k, 11)/11 for i in 1:dom.Nu-1, j in 1:dom.Nv-1, k in 1:dom.Nw-1]

"""A material array in `config.material` layout with `vals` in `slot`, ones elsewhere."""
function _mm_material(dom, slot, vals)
    m = ones(dom.Nu-1, dom.Nv-1, dom.Nw-1, 3)
    m[:, :, :, slot] .= vals
    return m
end

"""Cell volumes, (Nu-1) × (Nv-1) × (Nw-1)."""
_mm_volumes(dom) = dom.edges_u .* dom.edges_v' .* reshape(dom.edges_w, 1, 1, :)

"""
Independent reference for the diagonal: loop over *cells* and scatter each cell's
quarter of the dual facet onto its four edges in each direction. There is no
padding and no dead edge is ever touched, so this shares no boundary logic with
the implementation. `mu`, `mv`, `mw` hold absolute values per cell.
"""
function _mm_reference(dom, mu, mv, mw)
    Np = dom.Np
    eu, ev, ew = dom.edges_u, dom.edges_v, dom.edges_w
    p(i, j, k) = _mm_idx(dom, i, j, k)
    d = zeros(promote_type(eltype(mu), eltype(mv), eltype(mw)), 3Np)
    for k in 1:dom.Nw-1, j in 1:dom.Nv-1, i in 1:dom.Nu-1
        for (b, c) in ((0, 0), (1, 0), (0, 1), (1, 1))
            d[      p(i,   j+b, k+c)] += mu[i, j, k] * ev[j]*ew[k] / 4 / eu[i]
            d[Np  + p(i+b, j,   k+c)] += mv[i, j, k] * eu[i]*ew[k] / 4 / ev[j]
            d[2Np + p(i+b, j+c, k  )] += mw[i, j, k] * eu[i]*ev[j] / 4 / ew[k]
        end
    end
    return d
end

"""
Parallel-plate capacitor filling the whole domain. The plates are the two w-faces,
Φ = 0 at the bottom and Φ = `V0` at the top. The four side faces are left natural,
i.e. magnetic walls, so there is no fringing and the exact field is one-dimensional.

Returns the charge on the top plate, the charge on the bottom plate, and the charge
at every free node, all obtained from Gauss's law ρ = S̃ d̂ with d̂ = M_ε ê.
"""
function _mm_plate_capacitor(dom, Mε, V0)
    G = get_ghost_matrix(dom) * get_gradient(dom, Primal())
    L = G' * Mε * G

    top   = get_boundary_indices(dom, DirZ(), Positive())[1]
    bot   = get_boundary_indices(dom, DirZ(), Negative())[1]
    fixed = vcat(top, bot)
    free  = setdiff(1:dom.Np, fixed)

    Φ = zeros(dom.Np)
    Φ[top] .= V0
    Φ[free] = cholesky(Symmetric(L[free, free])) \ (-(L[free, fixed] * Φ[fixed]))

    d̂ = Mε * (-(G * Φ))
    ρ = get_divergence(dom, Dual()) * d̂
    return sum(ρ[top]), sum(ρ[bot]), ρ[free]
end

"""
Net outward flux of d̂ through the surface of the node box I × J × K: every edge
leaving the box minus every edge entering it. This is ∮ D·dA written out edge by
edge, deliberately not via S̃.
"""
function _mm_box_flux(dom, d̂, I, J, K)
    Np = dom.Np
    p(i, j, k) = _mm_idx(dom, i, j, k)
    f = 0.0
    for j in J, k in K
        f += d̂[      p(last(I), j, k)] - d̂[      p(first(I)-1, j, k)]
    end
    for i in I, k in K
        f += d̂[Np  + p(i, last(J), k)] - d̂[Np  + p(i, first(J)-1, k)]
    end
    for i in I, j in J
        f += d̂[2Np + p(i, j, last(K))] - d̂[2Np + p(i, j, first(K)-1)]
    end
    return f
end

"""
Independent reference for the reluctivity diagonal: loop over cells, and give each
cell's two facets normal to a direction half of the cell length along it, weighted
by the cell's ν and divided by the facet area. `ν` holds absolute values per cell.
"""
function _mm_reluctivity_reference(dom, ν)
    Np = dom.Np
    eu, ev, ew = dom.edges_u, dom.edges_v, dom.edges_w
    p(i, j, k) = _mm_idx(dom, i, j, k)
    d = zeros(3Np)
    for k in 1:dom.Nw-1, j in 1:dom.Nv-1, i in 1:dom.Nu-1
        for s in (0, 1)
            d[      p(i+s, j, k)] += ν[i, j, k] * eu[i] / 2 / (ev[j] * ew[k])
            d[Np  + p(i, j+s, k)] += ν[i, j, k] * ev[j] / 2 / (eu[i] * ew[k])
            d[2Np + p(i, j, k+s)] += ν[i, j, k] * ew[k] / 2 / (eu[i] * ev[j])
        end
    end
    return d
end

"""Dead primal facets: the tangential facet components on the three positive faces."""
_mm_dead_facets(dom) = get_custom_boundary_indices(dom,
    [(DirX(), Positive()), (DirY(), Positive()), (DirZ(), Positive())], TangentialComponent())


@testset "material matrices" begin

g  = _MM_GRID
Np = g.Np
εu, εv, εw = _mm_field(g, 7, 13, 29), _mm_field(g, 3, 5, 17), _mm_field(g, 11, 2, 19)
Mε_aniso   = _MM(g, 2, _mm_material(g, 2, εu), _mm_material(g, 2, εv), _mm_material(g, 2, εw))

# ---------------------------------------------------------------------------
# Values
# ---------------------------------------------------------------------------

@testset "uniform grid: interior entries" begin
    # moved from runtests.jl; own domain so this file also runs on its own
    U  = create_domain([6.0, 8.0, 10.0], [2.0, 2.0, 2.0]; units = "m")
    ν₀ = 1 / FITToolbox.μ₀
    p  = _mm_idx(U, 2, 2, 2)                  # interior node

    # M_ε: dual facet area / primal edge length, times ε₀
    @test get_permittivity(U)[p, p] ≈ _ε₀ * 4.0 / 2.0
    # M_ν: dual edge length / primal facet area, times ν₀
    @test get_reluctivity(U)[p, p]  ≈ ν₀ * 2.0 / 4.0
    # vacuum background: conductivity is zero everywhere
    @test iszero(get_conductivity(U))
end

@testset "graded grid: interior entry" begin
    # moved from the non-equidistant grid test in runtests.jl
    N  = create_domain([1.0, 2.0, 4.0], [0.5, 1.0, 2.0, 4.0], [3.0, 1.0, 2.0]; units = "m")
    p  = _mm_idx(N, 2, 2, 2)
    @test get_permittivity(N)[p, p] ≈ _ε₀ * (N.dual_edges_v[2] * N.dual_edges_w[2]) / N.edges_u[2]
end

@testset "vacuum: boundary edges get the truncated dual facet" begin
    d   = diag(get_permittivity(g))
    ref = zeros(3Np)
    for k in 1:g.Nw, j in 1:g.Nv, i in 1:g.Nu
        p = _mm_idx(g, i, j, k)
        i < g.Nu && (ref[p]       = _ε₀ * g.dual_facets_u[j, k] / g.edges_u[i])
        j < g.Nv && (ref[p + Np]  = _ε₀ * g.dual_facets_v[i, k] / g.edges_v[j])
        k < g.Nw && (ref[p + 2Np] = _ε₀ * g.dual_facets_w[i, j] / g.edges_w[k])
    end
    @test d ≈ ref
    # exactly zero on the dead edges, and nowhere else
    @test findall(iszero, d) == get_ghost_indices(g)
end

@testset "inhomogeneous, anisotropic: matches the cell-wise reference" begin
    @test diag(Mε_aniso) ≈ _mm_reference(g, _ε₀ .* εu, _ε₀ .* εv, _ε₀ .* εw)
    @test all(iszero, diag(Mε_aniso)[get_ghost_indices(g)])

    σ  = _mm_field(g, 5, 7, 3)
    mσ = _mm_material(g, 1, σ)
    @test diag(_MM(g, 1, mσ, mσ, mσ)) ≈ _mm_reference(g, σ, σ, σ)

    # the isotropic two-argument form reads config.material
    h = create_domain(g.edges_u, g.edges_v, g.edges_w; units = "m")
    h.material[:, :, :, 2] .= εu
    h.material[:, :, :, 1] .= σ
    @test diag(get_permittivity(h))  ≈ _mm_reference(h, _ε₀ .* εu, _ε₀ .* εu, _ε₀ .* εu)
    @test diag(get_conductivity(h))  ≈ _mm_reference(h, σ, σ, σ)
end

@testset "argument checks" begin
    m = g.material
    @test_throws ArgumentError     _MM(g, 0)
    @test_throws ArgumentError     _MM(g, 3)
    @test_throws DimensionMismatch _MM(g, 2, ones(g.Nu, g.Nv-1, g.Nw-1, 3), m, m)
    @test_throws DimensionMismatch _MM(g, 2, m, m, ones(g.Nu-1, g.Nv-1, g.Nw-1, 2))
end

@testset "element type" begin
    mi = ones(Int, g.Nu-1, g.Nv-1, g.Nw-1, 3)
    Mi = _MM(g, 2, mi, mi, mi)
    @test eltype(Mi) == Float64
    @test Mi ≈ get_permittivity(g)

    mc = complex.(g.material, 0.5 .* g.material)
    Mc = _MM(g, 2, mc, mc, mc)
    @test eltype(Mc) == ComplexF64
    @test real(diag(Mc)) ≈ diag(get_permittivity(g))
    @test imag(diag(Mc)) ≈ 0.5 .* diag(get_permittivity(g))
end

# ---------------------------------------------------------------------------
# Physics
# ---------------------------------------------------------------------------

@testset "energy and Joule power of a uniform field" begin
    # Φ = -E·r gives ê = -GΦ with E_u·Δu on every u-edge, and so on. The quarters
    # of the dual facets tile every cell exactly once per direction, so
    #   ½ êᵀ M_ε ê = ½ ∑_cells (ε_uu E_u² + ε_vv E_v² + ε_ww E_w²) V_cell
    # holds to rounding on any grid, with any cell-wise material. Doubled boundary
    # facets overestimate it by the boundary shell (28 % on this grid).
    E  = (1.3, -0.7, 2.1)
    xu = reshape(g.nodes_u, :, 1, 1)
    xv = reshape(g.nodes_v, 1, :, 1)
    xw = reshape(g.nodes_w, 1, 1, :)
    Φ  = vec(-(E[1] .* xu .+ E[2] .* xv .+ E[3] .* xw))
    Vc = _mm_volumes(g)

    # Unprojected on purpose: the dead rows of G are wrapped differences between
    # unrelated nodes, and only the zero in M_ε keeps them out of the energy.
    G = get_gradient(g, Primal())
    ê = -(G * Φ)

    W_fit   = dot(ê, Mε_aniso * ê) / 2
    W_exact = _ε₀ * sum((εu .* E[1]^2 .+ εv .* E[2]^2 .+ εw .* E[3]^2) .* Vc) / 2
    @test W_fit ≈ W_exact rtol = 1e-12

    σ  = _mm_field(g, 5, 7, 3)
    mσ = _mm_material(g, 1, σ)
    @test dot(ê, _MM(g, 1, mσ, mσ, mσ) * ê) ≈ sum(σ .* Vc) * sum(abs2, E) rtol = 1e-12

    # consequence: the ghost projection no longer changes the system matrix
    Gh = get_ghost_matrix(g) * G
    @test G' * Mε_aniso * G ≈ Gh' * Mε_aniso * Gh
end

@testset "parallel-plate capacitor: Q from Gauss's law equals C·V exactly" begin
    # On this grid the old boundary treatment overestimates Q by 82 % (vacuum),
    # 37 % (series) and 25 % (parallel).
    V0 = 3.0
    A  = sum(g.edges_u) * sum(g.edges_v)
    d  = sum(g.edges_w)
    cells(f) = [f(i, j, k) for i in 1:g.Nu-1, j in 1:g.Nv-1, k in 1:g.Nw-1]

    # vacuum: C = ε₀ A / d
    Qt, Qb, ρ_free = _mm_plate_capacitor(g, get_permittivity(g), V0)
    @test Qt ≈ _ε₀ * A / d * V0 rtol = 1e-10
    @test Qb ≈ -Qt rtol = 1e-10
    # div D = 0 in the gap, including on the magnetic walls
    @test norm(ρ_free, Inf) ≤ 1e-10 * abs(Qt)

    # series: layers stacked along w, C = ε₀ A / ∑ (Δw_k / ε_k).
    # The in-plane components are set to unrelated values: the plate field has no
    # u or v voltage, so only ε_ww may enter.
    εk      = [1.0, 4.0, 2.0, 7.0, 3.0]
    @assert length(εk) == g.Nw - 1
    εs      = cells((i, j, k) -> εk[k])
    in_plane = cells((i, j, k) -> 10.0 + i + 2j)
    Mε = _MM(g, 2, _mm_material(g, 2, in_plane), _mm_material(g, 2, in_plane), _mm_material(g, 2, εs))
    Qt, Qb, _ = _mm_plate_capacitor(g, Mε, V0)
    @test Qt ≈ _ε₀ * A / sum(g.edges_w ./ εk) * V0 rtol = 1e-10
    @test Qb ≈ -Qt rtol = 1e-10

    # parallel: columns side by side along u, the outer ones touching the side
    # walls, C = ε₀ ∑ ε_i Δu_i · Lv / d
    εi = [2.0, 5.0, 1.0, 3.0]
    @assert length(εi) == g.Nu - 1
    mp = _mm_material(g, 2, cells((i, j, k) -> εi[i]))
    Qt, Qb, _ = _mm_plate_capacitor(g, _MM(g, 2, mp, mp, mp), V0)
    @test Qt ≈ _ε₀ * sum(εi .* g.edges_u) * sum(g.edges_v) / d * V0 rtol = 1e-10
    @test Qb ≈ -Qt rtol = 1e-10
end

@testset "Gauss's law: flux through a closed dual surface equals the enclosed charge" begin
    # Holds for any M_ε, so this guards signs, orientation and the assembly and
    # solve chain rather than the averaging. Material is inhomogeneous and
    # anisotropic because Gauss's law must not care.
    G = get_ghost_matrix(g) * get_gradient(g, Primal())
    L = G' * Mε_aniso * G

    faces = [(n, s) for n in (DirX(), DirY(), DirZ()) for s in (Positive(), Negative())]
    R  = get_boundary_matrix(g, faces, NodalComponent())
    Dm = Diagonal(ones(Np)) - R

    q0 = 1.602e-19
    q  = zeros(Np)
    q[_mm_idx(g, 3, 2, 4)] = q0

    Φ = cholesky(Dm + R*L*R; check = true) \ (R*q)
    d̂ = Mε_aniso * (-(G * Φ))

    @test _mm_box_flux(g, d̂, 3:3, 2:2, 4:4) ≈ q0 rtol = 1e-10    # the charge's own dual cell
    @test _mm_box_flux(g, d̂, 3:4, 2:3, 3:4) ≈ q0 rtol = 1e-10    # off-centre box around it
    @test _mm_box_flux(g, d̂, 2:4, 2:3, 2:5) ≈ q0 rtol = 1e-10    # every interior node
    @test abs(_mm_box_flux(g, d̂, 4:4, 2:3, 2:5)) ≤ 1e-10 * q0    # a box that misses it

    # the same statement in operator form: S̃ d̂ = q at every free node
    @test R * (get_divergence(g, Dual()) * d̂) ≈ q rtol = 1e-10
end

# ---------------------------------------------------------------------------
# Reluctivity
# ---------------------------------------------------------------------------

@testset "reluctivity: boundary dual edges and dead facets" begin
    ν₀  = 1 / FITToolbox.μ₀
    Mν  = get_reluctivity(g)
    d   = diag(Mν)
    ref = zeros(3Np)
    for k in 1:g.Nw, j in 1:g.Nv, i in 1:g.Nu
        p = _mm_idx(g, i, j, k)
        j < g.Nv && k < g.Nw && (ref[p]       = ν₀ * g.dual_edges_u[i] / g.primal_facets_u[j, k])
        i < g.Nu && k < g.Nw && (ref[p + Np]  = ν₀ * g.dual_edges_v[j] / g.primal_facets_v[i, k])
        i < g.Nu && j < g.Nv && (ref[p + 2Np] = ν₀ * g.dual_edges_w[k] / g.primal_facets_w[i, j])
    end
    @test size(Mν) == (3Np, 3Np)
    @test eltype(Mν) == Float64
    @test d ≈ ref
    # exactly zero on the dead facets, and nowhere else
    @test findall(iszero, d) == _mm_dead_facets(g)
end

@testset "reluctivity: inhomogeneous μ_r matches the cell-wise reference" begin
    # non-uniform, reaching the boundary; catches μ_r/μ₀ in place of 1/(μ₀ μ_r)
    μr = _mm_field(g, 7, 13, 29)
    h  = create_domain(g.edges_u, g.edges_v, g.edges_w; units = "m")
    h.material[:, :, :, 3] .= μr
    d  = diag(get_reluctivity(h))
    @test d ≈ _mm_reluctivity_reference(h, 1 ./ (FITToolbox.μ₀ .* μr))
    @test findall(iszero, d) == _mm_dead_facets(h)

    # uniform μ_r scales every entry by 1/μ_r
    h.material[:, :, :, 3] .= 4.0
    @test get_reluctivity(h) ≈ get_reluctivity(g) ./ 4
end

@testset "reluctivity: argument checks" begin
    for bad_value in (0.0, -1.0, NaN)
        bad = create_domain(g.edges_u, g.edges_v, g.edges_w; units = "m")
        bad.material[2, 1, 1, 3] = bad_value
        @test_throws ArgumentError get_reluctivity(bad)
    end
end

end
