#This file was generated by Opus 5.0
#10/08/2026
using FITToolbox, Test, LinearAlgebra, SparseArrays
using CairoMakie

# Non-cubic everywhere. A 10×10×10 grid hides exactly the stride bugs you
# most want to catch, because Nu, Nv and Nw become interchangeable.
const D = create_domain([6.0, 8.0, 10.0], [2.0, 2.0, 2.0]; units="m")

@testset "FITToolbox" begin

@test FITToolbox.ε₀ * FITToolbox.μ₀ ≈ 1/299792458.0^2 rtol=1e-9

@testset "grid arithmetic" begin
    @test (D.Nu, D.Nv, D.Nw) == (4, 5, 6)
    @test D.Np == 120
    @test length(D.edges_u) == D.Nu - 1
    @test sum(D.edges_u) ≈ 6.0
    @test length(D.dual_edges_u) == D.Nu
    @test sum(D.dual_edges_u) ≈ 6.0        # dual edges tile the same extent
    # the float-division case that used to throw InexactError
    @test create_domain([0.3, 1.0, 1.0], [0.1, 0.1, 0.1]).Nu == 4
end

@testset "operator identities" begin
    C, G, S = get_curl(D, Primal()), get_gradient(D, Primal()), get_divergence(D, Primal())
    @test iszero(C * G)                    # curl grad = 0
    @test iszero(S * C)                    # div curl = 0
    @test get_curl(D, Dual())       ≈ C'
    @test get_divergence(D, Dual()) ≈ -G'
    @test get_gradient(D, Dual())   ≈ -S'
end

@testset "system matrix" begin
    Gh = get_ghost_matrix(D) * get_gradient(D, Primal())
    L  = Gh' * get_permittivity(D) * Gh
    @test issymmetric(L)
    @test norm(L * ones(D.Np)) == 0        # exact: rows are ±1
    @test rank(Matrix(L)) == D.Np - 1      # connected grid, one-dim null space
end

@testset "Dirichlet flux balance" begin
    Gh = get_ghost_matrix(D) * get_gradient(D, Primal())
    L  = Gh' * get_permittivity(D) * Gh
    faces = [(DirX(),Positive()),(DirX(),Negative()),(DirY(),Positive()),
             (DirY(),Negative()),(DirZ(),Positive()),(DirZ(),Negative())]
    R = get_boundary_matrix(D, faces, NodalComponent())
    Dm = Diagonal(ones(D.Np)) - R

    q = zeros(D.Np)
    q[get_index_entity(D, DualVolume(), 2.0, 4.0, 4.0)] = 1.602e-19

    Φ = cholesky(Dm + R*L*R; check=true) \ (R*q)
    @test sum(Dm * (L * Φ)) ≈ -sum(q) rtol=1e-6
end

@testset "interpolation reproduces a linear field" begin
    f = zeros(D.Np)
    for k = 1:D.Nw-1, j = 1:D.Nv-1, i = 1:D.Nu-1
        p = 1 + (i-1) + (j-1)*D.Nu + (k-1)*D.Nu*D.Nv
        f[p] = 2*D.edges_u_center[i] + 3*D.edges_v_center[j] - D.edges_w_center[k]
    end
    x, y, z = 2.3, 3.7, 4.1
    @test interpolate(D, DualNode(), f, x, y, z) ≈ 2x + 3y - z atol=1e-12
end

@testset "CFL" begin
    U = create_domain([4.0, 4.0, 4.0], [2.0, 2.0, 2.0])
    c = 1/sqrt(8.8541878188e-12 * 4π*1e-7)
    @test get_vacuum_cfl_time(U) ≈ 2.0/(c*sqrt(3)) rtol=1e-12
end

@testset "exports resolve" begin
    for n in names(FITToolbox)
        @test isdefined(FITToolbox, n)
    end
end

@testset "ghost indices" begin
    # one dead edge per node on the far plane, in each of the three directions
    @test length(get_ghost_indices(D)) == D.Nv*D.Nw + D.Nu*D.Nw + D.Nu*D.Nv
    @test all(1 .<= get_ghost_indices(D) .<= 3*D.Np)
end

@testset "create_cube!" begin
    d = create_domain([6.0, 8.0, 10.0], [2.0, 2.0, 2.0])
    create_cube!(d, 0.0, 0.0, 0.0, 4.0, 4.0, 4.0; ε_r=5.0)
    @test all(d.material[1:2, 1:2, 1:2, 2] .== 5.0)   # cells inside the cube
    @test d.material[3, 1, 1, 2] == 1.0               # outside keeps background
end

@testset "create_sphere!" begin
    d = create_domain([6.0, 8.0, 10.0], [2.0, 2.0, 2.0])
    create_sphere!(d, 3.0, 4.0, 5.0, 2.0; ε_r=5.0, μ_r=2.0)
    @test any(d.material[:,:,:,2] .== 5.0)     # something was filled
    @test any(d.material[:,:,:,2] .== 1.0)     # but not everything
end

@testset "check_units" begin
    @test FITToolbox.check_units("m")  == 1.0
    @test FITToolbox.check_units("mm") == 1e-3
    @test FITToolbox.check_units("μm") == 1e-6    # U+03BC greek mu
    @test FITToolbox.check_units("µm") == 1e-6    # U+00B5 micro sign
end

@testset "dual volumes sit on primal nodes" begin
    p = get_index_entity(D, DualVolume(), 2.0, 4.0, 4.0)
    @test p == 1 + 1 + 2*D.Nu + 2*D.Nu*D.Nv
    @test p == get_index_entity(D, PrimalNode(), 2.0, 4.0, 4.0)
end

@testset "non-equidistant grid" begin
    # deliberately irregular, and different in each direction
    eu = [1.0, 2.0, 4.0]
    ev = [0.5, 1.0, 2.0, 4.0]
    ew = [3.0, 1.0, 2.0]
    N = create_domain(eu, ev, ew; units="m")

    @test (N.Nu, N.Nv, N.Nw) == (4, 5, 4)
    @test N.nodes_u ≈ [0.0, 1.0, 3.0, 7.0]
    @test N.edges_u_center ≈ [0.5, 2.0, 5.0]

    # dual edges: half-cells at the ends, half-sums inside
    @test N.dual_edges_u ≈ [0.5, 1.5, 3.0, 2.0]
    @test sum(N.dual_edges_u) ≈ sum(eu)

    # facets: primal_facets_u is (Nv-1)×(Nw-1), spanned by v and w edges
    @test N.primal_facets_u[2, 3] ≈ ev[2] * ew[3]
    @test N.primal_facets_v[3, 1] ≈ eu[3] * ew[1]
    @test N.primal_facets_w[1, 4] ≈ eu[1] * ev[4]

    # topology is metric-free, so the identities must still hold exactly
    C, G, S = get_curl(N, Primal()), get_gradient(N, Primal()), get_divergence(N, Primal())
    @test iszero(C * G)
    @test iszero(S * C)

    # the linear-field interpolation test, now on an irregular grid
    f = zeros(N.Np)
    for k = 1:N.Nw-1, j = 1:N.Nv-1, i = 1:N.Nu-1
        q = 1 + (i-1) + (j-1)*N.Nu + (k-1)*N.Nu*N.Nv
        f[q] = 2*N.edges_u_center[i] + 3*N.edges_v_center[j] - N.edges_w_center[k]
    end
    x, y, z = 1.7, 2.3, 2.9
    @test interpolate(N, DualNode(), f, x, y, z) ≈ 2x + 3y - z atol=1e-12
end

# M_ε, M_σ, M_ν: values, boundary treatment, dead entries, physics checks
include("indexing.jl")
include("interpolation_edges_facets.jl")
include("material_matrices.jl")
include("sources.jl")

@testset "plotting extension" begin
    # The extension loaded: without it, plot_nodal_values has zero methods.
    @test length(methods(plot_nodal_values)) == 1

    # A smooth analytic field, so the heatmap has a real range to scale.
    # i runs fastest, matching the node index p = i + (j-1)Nu + (k-1)NuNv.
    f = [2*D.nodes_u[i] + 3*D.nodes_v[j] - D.nodes_w[k]
         for i in 1:D.Nu, j in 1:D.Nv, k in 1:D.Nw] |> vec

    fig = plot_nodal_values(D, Primal(), f, DirZ(); pos = 4.0)
    @test fig isa Figure

    # Exercises the gradient/streamplot branch and the PrimalEdge path.
    fig2 = plot_nodal_values(D, Primal(), f, DirZ();
                             pos = 4.0, plot_negative_gradient = true)
    @test fig2 isa Figure

    @test_throws DimensionMismatch plot_nodal_values(D, Primal(), f[1:end-1], DirZ())
end

end