#This file was generated by Claude Opus 5.5
#05/10/2026
#
# Tests for save_domain / load_domain (SaveLoad.jl): round trip of grid, background
# material and history, hand-written files, and invalid input.
# Included from runtests.jl.

using FITToolbox, Test

# an object type save_domain does not know, standing in for a future one that was
# not added to SaveLoad.jl (structs must be defined at top level)
struct _UnsavableObject <: FITToolbox.AbstractFITObject end

# a domain with every object type, a named and an unnamed object, a colour,
# and a removed object, so the file contains a delete step
function _saveload_domain(d)
    create_brick!(d, 0, 0, 0, 4, 4, 4; σ=5.8e7, name="plate", color="copper")
    create_sphere!(d, 3, 4, 5, 2.5; ε_r=7.0, μ_r=3.0)
    create_circular_loop_source!(d, 1.0, 3.0, 4.0, 5.0, DirX(); name="coil", current=250.0)
    create_brick!(d, 2, 2, 2, 2, 2, 6; μ_r=9.0)
    @test_logs remove_object!(d, 4)
    return d
end

@testset "save/load: round trip" begin
    d = _saveload_domain(create_domain([6.0, 8.0, 10.0], [0.5, 0.5, 0.5]; σ=0.1, ε_r=2.0))
    mktempdir() do dir
        path = joinpath(dir, "model.toml")
        @test (@test_logs save_domain(path, d)) == path              # clean domain: no warning
        e = @test_logs load_domain(path)

        @test (e.edges_u, e.edges_v, e.edges_w) == (d.edges_u, d.edges_v, d.edges_w)
        @test (e.σ, e.ε_r, e.μ_r) == (0.1, 2.0, 1.0)
        @test e.material == d.material
        @test e._history.steps == d._history.steps
        @test e._history.obj_counter == 4
        @test [x.name for x in list_objects(e)] == ["plate", "obj2", "coil"]
        @test get_source(e, "coil") == get_source(d, "coil")

        # the history works on as before: undo brings the removed brick back,
        # and the next object gets a new id
        @test_logs undo!(e)
        @test [x.obj_id for x in list_objects(e)] == [1, 2, 3, 4]
        @test create_sphere!(e, 3, 4, 5, 1.0) == 5

        # the original is untouched
        @test length(d._history.steps) == 5
    end
end

@testset "save/load: non-equidistant grid and empty domain" begin
    eu = [1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0]
    ev = [2.0, 1.0, 0.5, 0.5, 0.5, 0.5, 1.0, 2.0]
    ew = fill(0.5, 20)
    g = _saveload_domain(create_domain(eu, ev, ew))
    empty = create_domain([6.0, 8.0, 10.0], [2.0, 2.0, 2.0]; μ_r=4.0)
    mktempdir() do dir
        e = load_domain(save_domain(joinpath(dir, "graded.toml"), g))
        @test e.edges_u == eu && e.edges_v == ev && e.edges_w == ew
        @test e.material == g.material

        e = load_domain(save_domain(joinpath(dir, "empty.toml"), empty))
        @test isempty(e._history.steps)
        @test e.material == empty.material
        @test length(list_objects(e)) == 0
    end
end

@testset "save/load: hand-written file" begin
    # integers where floats are stored, keys in any order, no colour
    text = """
        format_version = 1

        [domain]
        edges_u = [2, 2, 2]
        edges_v = [2, 2, 2, 2]
        edges_w = [2, 2, 2, 2, 2]
        sigma = 0
        eps_r = 1
        mu_r = 1
        obj_counter = 1

        [[steps]]
        op = "create"
        obj_id = 1
        name = "block"
        type = "Brick"
        origin = [0, 0, 0]
        lengths = [4, 4, 4]
        sigma = 10
        eps_r = 1
        mu_r = 1
        """
    mktempdir() do dir
        path = joinpath(dir, "hand.toml")
        write(path, text)
        e = load_domain(path)
        d = create_domain([6.0, 8.0, 10.0], [2.0, 2.0, 2.0])
        create_brick!(d, 0, 0, 0, 4, 4, 4; σ=10.0, name="block")
        @test e.material == d.material
        @test only(list_objects(e)).name == "block"
    end
end

@testset "save/load: manually set material values" begin
    d = create_domain([6.0, 8.0, 10.0], [2.0, 2.0, 2.0])
    create_brick!(d, 0, 0, 0, 4, 4, 4; σ=5.0)
    clean = copy(d.material)
    d.material[1, 1, 1, 2] = 42.0
    mktempdir() do dir
        path = joinpath(dir, "manual.toml")
        @test_logs (:warn, r"not saved") save_domain(path, d)
        @test load_domain(path).material == clean
        @test d.material[1, 1, 1, 2] == 42.0                             # original untouched
    end
end

@testset "save/load: invalid files" begin
    mktempdir() do dir
        bad(name, text) = (p = joinpath(dir, name); write(p, text); p)
        domain = """
            [domain]
            edges_u = [2.0, 2.0, 2.0]
            edges_v = [2.0, 2.0, 2.0, 2.0]
            edges_w = [2.0, 2.0, 2.0, 2.0, 2.0]
            sigma = 0.0
            eps_r = 1.0
            mu_r = 1.0
            obj_counter = 1
            """

        @test_throws ArgumentError load_domain(bad("none.toml", "x = 1\n"))
        @test_throws ArgumentError load_domain(bad("v2.toml", "format_version = 2\n" * domain))

        # unknown step op, e.g. a typo for "delete": not read as "create"
        @test_throws ArgumentError load_domain(bad("op.toml", "format_version = 1\n" * domain * """

            [[steps]]
            op = "remove"
            obj_id = 1
            name = "plate"
            type = "Brick"
            origin = [0.0, 0.0, 0.0]
            lengths = [2.0, 2.0, 2.0]
            sigma = 1.0
            eps_r = 1.0
            mu_r = 1.0
            """))

        # unknown object type
        @test_throws ArgumentError load_domain(bad("cone.toml", "format_version = 1\n" * domain * """

            [[steps]]
            op = "create"
            obj_id = 1
            name = "cone"
            type = "Cone"
            """))

        # a brick outside the grid: _replay! refuses it
        @test_throws ArgumentError load_domain(bad("outside.toml", "format_version = 1\n" * domain * """

            [[steps]]
            op = "create"
            obj_id = 1
            name = "far"
            type = "Brick"
            origin = [100.0, 0.0, 0.0]
            lengths = [2.0, 2.0, 2.0]
            sigma = 1.0
            eps_r = 1.0
            mu_r = 1.0
            """))
    end
end

@testset "save/load: complex current" begin
    d = create_domain([1.0, 1.0, 1.0], [0.1, 0.1, 0.1])
    create_circular_loop_source!(d, 0.2, 0.3, 0.5, 0.5, DirX(); current=250 - 30im, name="ac")
    create_circular_loop_source!(d, 0.2, 0.6, 0.5, 0.5, DirX(); current=100, name="dc")
    create_circular_loop_source!(d, 0.2, 0.5, 0.5, 0.5, DirX(); current=5 + 0im, name="zero_im")
    mktempdir() do dir
        path = save_domain(joinpath(dir, "complex.toml"), d)
        text = read(path, String)
        e = load_domain(path)

        @test e._history.steps == d._history.steps
        @test get_source(e, "ac") == get_source(d, "ac")
        @test eltype(get_source(e, "ac"))      == ComplexF64
        @test eltype(get_source(e, "dc"))      == Float64
        @test eltype(get_source(e, "zero_im")) == ComplexF64       # zero imaginary part stays complex

        # imaginary part as its own key, only for complex currents
        @test count("current_im", text) == 2
        @test occursin("current_im = -30.0", text)

        # a hand-written imaginary part, as an integer
        write(path, replace(text, "current_im = -30.0" => "current_im = 40"))
        @test only(x for x in list_objects(load_domain(path)) if x.name == "ac").object.current ==
              250.0 + 40.0im
    end
end

@testset "save/load: inconsistent steps" begin
    # files that are valid TOML but describe a history create_* and remove_object!
    # could never produce
    brick(id, name) = """

        [[steps]]
        op = "create"
        obj_id = $id
        name = "$name"
        type = "Brick"
        origin = [0.0, 0.0, 0.0]
        lengths = [2.0, 2.0, 2.0]
        sigma = 1.0
        eps_r = 1.0
        mu_r = 1.0
        """
    delete(id) = "\n[[steps]]\nop = \"delete\"\nobj_id = $id\n"
    file(counter, steps...) = """
        format_version = 1

        [domain]
        edges_u = [2.0, 2.0, 2.0]
        edges_v = [2.0, 2.0, 2.0, 2.0]
        edges_w = [2.0, 2.0, 2.0, 2.0, 2.0]
        sigma = 0.0
        eps_r = 1.0
        mu_r = 1.0
        obj_counter = $counter
        """ * join(steps)

    mktempdir() do dir
        load(text) = (p = joinpath(dir, "steps.toml"); write(p, text); load_domain(p))

        # two existing objects with one name
        @test_throws "already exists" load(file(2, brick(1, "a"), brick(2, "a")))
        # one obj_id created twice
        @test_throws "created twice" load(file(1, brick(1, "a"), brick(1, "b")))
        # deleting an object that does not exist, or no longer does
        @test_throws "does not exist" load(file(1, brick(1, "a"), delete(2)))
        @test_throws "does not exist" load(file(1, brick(1, "a"), delete(1), delete(1)))
        # a default name that belongs to another obj_id
        @test_throws "reserved" load(file(2, brick(1, "obj2")))
        # a counter that would hand out an existing id again
        @test_throws "obj_counter" load(file(1, brick(1, "a"), brick(2, "b")))
        # the message names the file
        @test_throws joinpath(dir, "steps.toml") load(file(2, brick(1, "a"), brick(2, "a")))

        # allowed: a name freed by a delete, and the default name of its own obj_id
        @test [x.name for x in list_objects(load(file(2, brick(1, "a"), delete(1), brick(2, "a"))))] == ["a"]
        @test [x.name for x in list_objects(load(file(1, brick(1, "obj1"))))] == ["obj1"]
    end
end

@testset "save/load: object type without save support" begin
    # not a solid, so the rebuild check in save_domain skips it and the error comes
    # from writing the step
    d = create_domain([6.0, 8.0, 10.0], [2.0, 2.0, 2.0])
    push!(d._history.steps, FITToolbox.CreateObject(1, "new", _UnsavableObject()))
    d._history.obj_counter = 1
    mktempdir() do dir
        path = joinpath(dir, "new.toml")
        @test_throws "cannot save objects of type _UnsavableObject" save_domain(path, d)
        @test !isfile(path)                      # nothing half-written
    end
end

@testset "save/load: cylinders" begin
    d = create_domain([1.0, 1.0, 1.0], [0.05, 0.05, 0.05])
    create_cylinder!(d, 0.5, 0.5, 0.1, 0.15, 0.3, DirZ(); σ = 5.8e7, name = "rod", color = "copper")
    create_cylinder!(d, 0.1, 0.3, 0.3, 0.1, 0.5, DirX(); ε_r = 4.0)
    create_cylinder!(d, 0.7, 0.1, 0.7, 0.05, 0.8, DirY(); μ_r = 100.0)
    mktempdir() do dir
        path = save_domain(joinpath(dir, "cyl.toml"), d)
        @test occursin("axis = \"DirY\"", read(path, String))
        e = load_domain(path)
        @test e._history.steps == d._history.steps
        @test e.material == d.material
    end
end
