#This file was generated by Opus 5.0
#11/09/2026
#
# Tests for create_circular_loop_source (CreateWire.jl). Included from runtests.jl.

using FITToolbox, Test, LinearAlgebra

# 1 m cells in u, 0.5 m in v and w: a loop of radius 8 m spans 16 cells, fine enough
# for the staircase to approximate the circle to about a percent.
const _WIRE_GRID = create_domain([20.0, 30.0, 30.0], [1.0, 0.5, 0.5]; units = "m")

"""Split a flat edge index into component (1 = u, 2 = v, 3 = w) and (i, j, k)."""
function _wire_ijk(d, p)
    b, q = divrem(p - 1, d.Np)
    k, r = divrem(q, d.Nu * d.Nv)
    j, i = divrem(r, d.Nu)
    return b + 1, i + 1, j + 1, k + 1
end

_wire_idx(d, b, i, j, k) = (b-1) * d.Np + i + (j-1)*d.Nu + (k-1)*d.Nu*d.Nv


@testset "circular loop source" begin

d = _WIRE_GRID
cu, cv, cw, R = 10.3, 15.2, 14.9, 8.0          # off-centre, so no symmetry hides a bug
J  = @test_logs create_circular_loop_source(d, R, cu, cv, cw, DirX())   # and no warnings
i0 = argmin(abs.(d.nodes_u .- cu))            # nearest node plane

@testset "a closed loop of unit edge currents in one u-plane" begin
    nz  = findall(!iszero, J)
    ijk = [_wire_ijk(d, p) for p in nz]
    @test !isempty(nz)
    @test all(x -> x == 1 || x == -1, J[nz])
    @test all(t -> t[1] != 1, ijk)             # no u-directed current
    @test all(t -> t[2] == i0, ijk)            # everything in the nearest node plane
    # current continuity GᵀJ = 0 at every node, exactly
    @test iszero(get_gradient(d, Primal())' * J)
end

@testset "one turn, counter-clockwise about +u" begin
    # w-currents through the line w = cw: +1 on the +v side, -1 on the -v side
    k0 = searchsortedlast(d.nodes_w, cw)
    @test sum(J[_wire_idx(d, 3, i0, j, k0)] for j in 1:d.Nv if d.nodes_v[j] > cv) == 1
    @test sum(J[_wire_idx(d, 3, i0, j, k0)] for j in 1:d.Nv if d.nodes_v[j] < cv) == -1
    # v-currents through the line v = cv: -1 on the +w side, +1 on the -w side
    j0 = searchsortedlast(d.nodes_v, cv)
    @test sum(J[_wire_idx(d, 2, i0, j0, k)] for k in 1:d.Nw if d.nodes_w[k] > cw) == -1
    @test sum(J[_wire_idx(d, 2, i0, j0, k)] for k in 1:d.Nw if d.nodes_w[k] < cw) == 1

    # enclosed area A = ½ ∮ (v dw − w dv) of the staircase: positive for this
    # orientation, and close to πR²
    A = 0.0
    for p in findall(!iszero, J)
        b, i, j, k = _wire_ijk(d, p)
        b == 3 && (A += J[p] * d.nodes_v[j] * d.edges_w[k] / 2)
        b == 2 && (A -= J[p] * d.nodes_w[k] * d.edges_v[j] / 2)
    end
    @test A ≈ π * R^2 rtol = 0.03
end

@testset "units" begin
    @test create_circular_loop_source(d, 8000.0, 10300.0, 15200.0, 14900.0, DirX(); units = "mm") == J
end

@testset "invalid requests" begin
    @test_throws ArgumentError create_circular_loop_source(d, R, cu, cv, cw, DirY())
    @test_throws ArgumentError create_circular_loop_source(d, R, cu, cv, cw, DirZ())

    # does not fit
    @test_throws ArgumentError create_circular_loop_source(d, R, 19.5, cv, cw, DirX())   # plane beyond nodes_u[end-2]
    @test_throws ArgumentError create_circular_loop_source(d, R, cu, 25.0, cw, DirX())   # v + R beyond the domain
    @test_throws ArgumentError create_circular_loop_source(d, R, cu, cv, 5.0, DirX())    # w − R below zero

    # smaller than a cell: nothing to mark, with a warning
    J0 = @test_logs (:warn, r"No edges") create_circular_loop_source(d, 0.1, 10.0, 15.0, 15.0, DirX())
    @test iszero(J0)
end

end