#This file was generated by Opus 5.0
#11/09/2026
#
# Tests for create_circular_loop_source! (CreateWire.jl). Included from runtests.jl.

using FITToolbox, Test, LinearAlgebra
using FITToolbox: CircularLoop

# 1 m cells in u, 0.5 m in v and w: a loop of radius 8 m spans 16 cells, fine enough
# for the staircase to approximate the circle to about a percent.
const _WIRE_GRID = create_domain([20.0, 30.0, 30.0], [1.0, 0.5, 0.5]; units = "m")

"""Split a flat edge index into component (1 = u, 2 = v, 3 = w) and (i, j, k)."""
function _wire_ijk(d, p)
    b, q = divrem(p - 1, d.Np)
    k, r = divrem(q, d.Nu * d.Nv)
    j, i = divrem(r, d.Nu)
    return b + 1, i + 1, j + 1, k + 1
end

_wire_idx(d, b, i, j, k) = (b-1) * d.Np + i + (j-1)*d.Nu + (k-1)*d.Nu*d.Nv

# add a loop to d and return its source vector
_loop_source(d, args...; kw...) = get_source(d, create_circular_loop_source!(d, args...; kw...))


@testset "circular loop source" begin

d = _WIRE_GRID
cu, cv, cw, R = 10.3, 15.2, 14.9, 8.0          # off-centre, so no symmetry hides a bug
J  = @test_logs _loop_source(d, R, cu, cv, cw, DirX())                  # and no warnings
i0 = argmin(abs.(d.nodes_u .- cu))            # nearest node plane

@testset "a closed loop of unit edge currents in one u-plane" begin
    nz  = findall(!iszero, J)
    ijk = [_wire_ijk(d, p) for p in nz]
    @test !isempty(nz)
    @test all(x -> x == 1 || x == -1, J[nz])
    @test all(t -> t[1] != 1, ijk)             # no u-directed current
    @test all(t -> t[2] == i0, ijk)            # everything in the nearest node plane
    # current continuity GᵀJ = 0 at every node, exactly
    @test iszero(get_gradient(d, Primal())' * J)
end

@testset "one turn, counter-clockwise about +u" begin
    # w-currents through the line w = cw: +1 on the +v side, -1 on the -v side
    k0 = searchsortedlast(d.nodes_w, cw)
    @test sum(J[_wire_idx(d, 3, i0, j, k0)] for j in 1:d.Nv if d.nodes_v[j] > cv) == 1
    @test sum(J[_wire_idx(d, 3, i0, j, k0)] for j in 1:d.Nv if d.nodes_v[j] < cv) == -1
    # v-currents through the line v = cv: -1 on the +w side, +1 on the -w side
    j0 = searchsortedlast(d.nodes_v, cv)
    @test sum(J[_wire_idx(d, 2, i0, j0, k)] for k in 1:d.Nw if d.nodes_w[k] > cw) == -1
    @test sum(J[_wire_idx(d, 2, i0, j0, k)] for k in 1:d.Nw if d.nodes_w[k] < cw) == 1

    # enclosed area A = ½ ∮ (v dw − w dv) of the staircase: positive for this
    # orientation, and close to πR²
    A = 0.0
    for p in findall(!iszero, J)
        b, i, j, k = _wire_ijk(d, p)
        b == 3 && (A += J[p] * d.nodes_v[j] * d.edges_w[k] / 2)
        b == 2 && (A -= J[p] * d.nodes_w[k] * d.edges_v[j] / 2)
    end
    @test A ≈ π * R^2 rtol = 0.03
end

@testset "units" begin
    @test _loop_source(d, 8000.0, 10300.0, 15200.0, 14900.0, DirX(); units = "mm") == J
end

@testset "invalid requests" begin
    # does not fit
    @test_throws ArgumentError create_circular_loop_source!(d, R, 19.5, cv, cw, DirX())   # plane beyond nodes_u[end-2]
    @test_throws ArgumentError create_circular_loop_source!(d, R, cu, 25.0, cw, DirX())   # v + R beyond the domain
    @test_throws ArgumentError create_circular_loop_source!(d, R, cu, cv, 5.0, DirX())    # w − R below zero
    @test_throws "u-direction" create_circular_loop_source!(d, R, cu, cv, cw, DirY())     # u + R = 18.3 > 18
    @test_throws "w-direction" create_circular_loop_source!(d, 5.0, cu, cv, 29.5, DirZ()) # plane beyond nodes_w[end-2]
    @test_throws "radius must be positive" create_circular_loop_source!(d, -1.0, cu, cv, cw, DirX())

    # smaller than a cell: nothing to mark, with a warning
    id0 = @test_logs (:warn, r"No edges") create_circular_loop_source!(d, 0.1, 10.0, 15.0, 15.0, DirX())
    J0  = @test_logs (:warn, r"No edges") get_source(d, id0)
    @test iszero(J0)
end

@testset "all three normals" begin
    # cubic grid, off-centre loop: m = ½ Σ r × dl over the marked edges is the
    # magnetic moment of the staircase; for a positive current it points along the
    # normal, with magnitude close to πR²
    g = create_domain([30.0, 30.0, 30.0], [0.5, 0.5, 0.5])
    function moment(J)
        nodes, edges = (g.nodes_u, g.nodes_v, g.nodes_w), (g.edges_u, g.edges_v, g.edges_w)
        m = zeros(3)
        for p in findall(!iszero, J)
            b, i, j, k = _wire_ijk(g, p)
            from = [nodes[a][(i, j, k)[a]] for a in 1:3]
            dl = [a == b ? edges[a][(i, j, k)[a]] : 0.0 for a in 1:3]
            m .+= cross(from .+ dl ./ 2, dl) .* (J[p] / 2)
        end
        return m
    end
    centre = (14.3, 15.2, 14.9)
    for (a, normal) in enumerate((DirX(), DirY(), DirZ()))
        Jn = @test_logs _loop_source(g, 8.0, centre..., normal)          # and no warnings
        @test iszero(get_gradient(g, Primal())' * Jn)                     # closed
        @test all(x -> x == 1 || x == -1, Jn[findall(!iszero, Jn)])
        m = moment(Jn)
        @test m[a] ≈ π * 8.0^2 rtol = 0.03                               # along +normal
        @test all(b -> abs(m[b]) < 1e-9 * m[a], filter(!=(a), 1:3))
        # only in-plane edges, all in the node plane nearest to the centre
        nz = [_wire_ijk(g, p) for p in findall(!iszero, Jn)]
        @test all(t -> t[1] != a, nz)
        plane = argmin(abs.((g.nodes_u, g.nodes_v, g.nodes_w)[a] .- centre[a]))
        @test all(t -> t[a + 1] == plane, nz)
    end
end

@testset "complex current" begin
    # same grid and loop as above, in fresh domains so the shared grid stays clean
    mk() = create_domain([20.0, 30.0, 30.0], [1.0, 0.5, 0.5])
    loop!(d; kw...) = create_circular_loop_source!(d, 8.0, 10.3, 15.2, 14.9, DirX(); kw...)
    d = mk()
    unit = get_source(d, loop!(d))                              # 1 A, real

    # a phasor scales the unit loop; the vector becomes complex
    e  = mk()
    Jc = @test_logs get_source(e, loop!(e; current=250.0 - 30.0im))   # and no warnings
    @test Jc isa Vector{ComplexF64}
    @test Jc == (250.0 - 30.0im) .* unit
    @test real(Jc) == 250.0 .* unit && imag(Jc) == -30.0 .* unit
    @test iszero(get_gradient(e, Primal())' * Jc)               # still closed: GᵀJ = 0

    # the type follows the current, not its value: real stays real, complex stays complex
    for (I, T) in ((2, Float64), (2.5f0, Float64), (1.0 + 2.0im, ComplexF64),
                   (ComplexF32(1, 2), ComplexF64), (5.0 + 0.0im, ComplexF64))
        f = mk()
        id = loop!(f; current=I)
        @test only(list_objects(f)).object isa CircularLoop{T}
        @test eltype(get_source(f, id)) == T
        @test get_source(f, id) == I .* unit
    end

    # shown in the object table
    g = mk()
    loop!(g; current=250.0 - 30.0im, name="ac")
    @test occursin("I=250.0 - 30.0im A", repr(MIME"text/plain"(), list_objects(g)))
end

@testset "deprecated create_circular_loop_source" begin
    mk() = create_domain([20.0, 30.0, 30.0], [1.0, 0.5, 0.5])

    # still returns the source vector, as before 0.3.0
    d = mk()
    J = @test_deprecated create_circular_loop_source(d, 8.0, 10.3, 15.2, 14.9, DirX();
                                                     current=1000.0, name="coil")
    e = mk()
    @test J == get_source(e, create_circular_loop_source!(e, 8.0, 10.3, 15.2, 14.9, DirX();
                                                          current=1000.0))

    # and records the loop like the new function
    @test only(list_objects(d)).name == "coil"
    @test get_source(d, "coil") == J
end

end
