#This file was generated by Claude Opus 5.5
#06/10/2026
#
# Tests for view_domain (ext/ViewDomain.jl) that need no rendering: CI has no GPU,
# so the 3D drawing itself is checked by hand with GLMakie. Included from runtests.jl,
# where CairoMakie is the active backend.

using FITToolbox, Test, CairoMakie, LinearAlgebra

const _VIEW = Base.get_extension(FITToolbox, :FITToolboxMakieExt)

_view_domain() = (d = create_domain([1.0, 1.0, 1.0], [0.05, 0.05, 0.05]);
                  create_brick!(d, 0.6, 0.1, 0.1, 0.1, 0.8, 0.8; σ = 5.8e7, name = "shield", color = "copper");
                  create_sphere!(d, 0.25, 0.5, 0.5, 0.15; ε_r = 4.0);
                  create_circular_loop_source!(d, 0.1, 0.4, 0.5, 0.5, DirX(); name = "coil");
                  d)

@testset "view_domain: refuses backends without depth buffer" begin
    d = _view_domain()
    @test_throws "CairoMakie cannot draw" view_domain(d)          # the active backend in the tests
    @test_throws "needs an active Makie backend" _VIEW._check_3d_backend(missing)
    @test _VIEW._check_3d_backend(Module(:GLMakie)) === nothing
end

@testset "view_domain: colours and toggle groups" begin
    d = _view_domain()
    entries = list_objects(d).entries
    colors = _VIEW._object_colors(entries)
    @test colors[1] == "#B87333"                                     # "copper", resolved
    @test colors[2] == Makie.wong_colors()[2]                        # no colour: palette
    @test colors[3] == Makie.wong_colors()[3]                        # sources too

    # up to 15 objects: one toggle per object, with its colour
    groups = _VIEW._toggle_groups(entries, colors)
    @test [g[1] for g in groups] == ["shield  (Brick)", "obj2  (Sphere)", "coil  (CircularLoop)"]
    @test [g[2] for g in groups] == [[1], [2], [3]]
    @test groups[1][3] == "#B87333"

    # more: one toggle per type, in order of first appearance
    m = create_domain([1.0, 1.0, 1.0], [0.05, 0.05, 0.05])
    for k in 1:20
        create_sphere!(m, 0.1 + 0.04k, 0.5, 0.5, 0.03)
    end
    create_brick!(m, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2)
    e = list_objects(m).entries
    groups = _VIEW._toggle_groups(e, _VIEW._object_colors(e))
    @test [g[1] for g in groups] == ["Sphere (20)", "Brick (1)"]
    @test groups[1][2] == collect(1:20) && groups[2][2] == [21]
    @test all(g -> g[3] === nothing, groups)
end

@testset "view_domain: cut" begin
    d = create_domain([0.4, 0.6, 1.0], [0.1, 0.2, 0.25])
    @test _VIEW._cut_positions(d, 1) == d.nodes_u
    @test _VIEW._cut_positions(d, 3) == d.nodes_w

    # the plane keeps what lies below the position and hides what lies beyond
    for axis in 1:3
        plane = _VIEW._clip_plane(axis, 0.3)
        below = Point3f(ntuple(i -> i == axis ? 0.2f0 : 0.5f0, 3))
        above = Point3f(ntuple(i -> i == axis ? 0.4f0 : 0.5f0, 3))
        @test !Makie.is_clipped(plane, below)
        @test Makie.is_clipped(plane, above)
    end

    # the outline of the cut: a closed rectangle in the plane, spanning the domain
    r = _VIEW._cut_rectangle((0, 0, 0), (0.4, 0.6, 1.0), 2, 0.3f0)
    @test length(r) == 5 && r[1] == r[end]
    @test all(p -> p[2] ≈ 0.3, r)
    @test extrema(p[1] for p in r) == (0, 0.4f0) && extrema(p[3] for p in r) == (0, 1.0f0)
end

@testset "view_domain: loop geometry" begin
    d = _view_domain()
    loop = only(e for e in list_objects(d) if e.name == "coil").object
    pts = _VIEW._loop_points(loop)
    @test all(p -> p[1] ≈ 0.4, pts)                                  # in its plane u = 0.4
    @test all(p -> isapprox(hypot(p[2] - 0.5, p[3] - 0.5), 0.1; rtol = 1e-5), pts)   # at its radius (Float32)
end

@testset "view_domain: grid in the cut plane" begin
    d = create_domain([0.4, 0.6, 1.0], [0.1, 0.2, 0.25])
    segs = _VIEW._cut_grid_segments(d, 2, 0.4)                       # cut along y
    @test length(segs) == 2 * (d.Nu + d.Nw)                          # one line per node of x and z
    @test all(p -> p[2] ≈ 0.4f0, segs)                               # all in the cut plane
    # lines at x = const span the full z range, lines at z = const the full x range
    @test Set(round(p[1]; digits = 4) for p in segs[1:2:2d.Nu]) == Set(round.(Float32.(d.nodes_u); digits = 4))
    @test extrema(p[3] for p in segs) == (0f0, 1f0) && extrema(p[1] for p in segs) == (0f0, 0.4f0)
end

@testset "view_domain: loop on its grid edges" begin
    d = create_domain([20.0, 30.0, 30.0], [1.0, 0.5, 0.5])          # the grid of sources.jl
    create_circular_loop_source!(d, 8.0, 10.3, 15.2, 14.9, DirX(); current = -3.0 + 2im, name = "coil")
    loop = only(list_objects(d)).object
    segs, mids, dirs = _VIEW._loop_edges(d, loop)
    J = get_source(d, "coil")
    @test length(segs) == 2 * count(!iszero, J)                      # one segment per marked edge
    @test all(i -> segs[2i] - segs[2i-1] == abs.(dirs[i]), eachindex(dirs))   # along the edge
    @test all(p -> p[1] ≈ d.nodes_u[argmin(abs.(d.nodes_u .- 10.3))], segs)  # in the loop's node plane

    # closed: every node is the end of an even number of edges
    ends = Dict{Point3f,Int}()
    foreach(p -> ends[p] = get(ends, p, 0) + 1, segs)
    @test all(iseven, values(ends))

    # the arrows circulate counter-clockwise about +u, independent of the complex
    # amplitude: enclosed area ½ Σ (v dw − w dv) > 0 and close to πR²
    A = sum((m[2] * dv[3] - m[3] * dv[2]) / 2 for (m, dv) in zip(mids, dirs))
    @test A ≈ π * 8.0^2 rtol = 0.03
end

@testset "view_domain: voxel labels" begin
    d = create_domain([1.0, 1.0, 1.0], [0.25, 0.25, 0.25])          # 4 × 4 × 4 cells
    create_brick!(d, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5; σ = 5.0)          # cells 1:2
    create_brick!(d, 0.25, 0.25, 0.25, 0.5, 0.5, 0.5; ε_r = 3.0)     # cells 2:3, overlaps
    create_brick!(d, 0.75, 0.75, 0.75, 0.25, 0.25, 0.25)             # removed below
    create_circular_loop_source!(d, 0.2, 0.25, 0.25, 0.25, DirX())   # no cells
    remove_object!(d, 3)
    lab = _VIEW._owner_labels(d)
    @test size(lab) == (4, 4, 4)
    @test lab[1, 1, 1] == 1 && lab[2, 2, 2] == 2 && lab[3, 3, 3] == 2   # the later object wins
    @test lab[4, 4, 4] == 0                                          # removed: background
    @test Set(lab) == Set([0, 1, 2])                                 # no label for the source
    # the labels follow the material exactly
    @test (lab .== 1) == (d.material[:, :, :, 1] .== 5.0)
    @test (lab .== 2) == (d.material[:, :, :, 2] .== 3.0)
end

@testset "view_domain: voxel surface meshes" begin
    faces(m) = length(m.faces) ÷ 2

    d = create_domain([0.3, 0.2, 0.2], [0.1, 0.1, 0.1])              # 3 × 2 × 2 cells
    lab = zeros(Int, 3, 2, 2)
    lab[1, 1, 1] = 7
    m = _VIEW._voxel_meshes(d, lab)
    @test keys(m) == Set([7]) && faces(m[7]) == 6                    # one cell: six faces
    # each face's normal points away from the cell centre
    centre = Point3f(0.05, 0.05, 0.05)
    @test all(m[7].faces) do f
        a, b, c = m[7].position[f[1]], m[7].position[f[2]], m[7].position[f[3]]
        dot(cross(b - a, c - a), (a + b + c) / 3 - centre) > 0
    end

    lab[2, 1, 1] = 7
    @test faces(_VIEW._voxel_meshes(d, lab)[7]) == 10                # the shared face is gone
    lab[2, 1, 1] = 8
    m = _VIEW._voxel_meshes(d, lab)
    @test faces(m[7]) == 6 && faces(m[8]) == 6                       # another object: both keep it

    # a cut after the first cell along x: the second one counts as empty
    lab .= 7
    @test _VIEW._cut_cells(d, 1, 0.1) == (1, 1)
    @test faces(_VIEW._voxel_meshes(d, lab; keep = _VIEW._cut_cells(d, 1, 0.1))[7]) ==
          2 * (2 * 2) + 2 * (1 * 2) + 2 * (1 * 2)                     # a 1 × 2 × 2 block
    @test isempty(_VIEW._voxel_meshes(d, lab; keep = _VIEW._cut_cells(d, 1, 0.0)))

    # graded grid: the corners are the node coordinates
    g = create_domain([0.1, 0.3], [0.2], [0.05, 0.05])
    m = _VIEW._voxel_meshes(g, fill(1, 2, 1, 2))[1]
    @test Set(p[1] for p in m.position) == Set(Float32[0, 0.1, 0.4])
    @test Set(p[3] for p in m.position) == Set(Float32[0, 0.05, 0.1])
end

@testset "view_domain: the figure and its controls" begin
    # built with CairoMakie, which cannot draw it but runs every callback
    d = create_domain([1.0, 1.0, 1.0], [0.05, 0.05, 0.05])
    create_brick!(d, 0.1, 0.1, 0.1, 0.8, 0.8, 0.1; σ = 5.8e7, name = "shield", color = "copper")
    create_sphere!(d, 0.5, 0.5, 0.55, 0.15; ε_r = 4.0, name = "ball")
    create_cylinder!(d, 0.2, 0.75, 0.2, 0.1, 0.6, DirZ(); name = "rod")
    create_circular_loop_source!(d, 0.1, 0.5, 0.5, 0.3, DirZ(); name = "coil")
    fig, st = _VIEW._view_figure(d)

    boxes  = [b for b in fig.content if b isa Checkbox]   # 4 objects, cut, grid, 2 loop options
    button(l) = only(b for b in fig.content if b isa Button && b.label[] == l)
    view_menu = only(b for b in fig.content if b isa Menu && "voxels" in b.options[])
    axis_menu = only(b for b in fig.content if b isa Menu && "y" in b.options[])
    slider = only(b for b in fig.content if b isa Slider)
    @test length(boxes) == 8
    visible(id) = sort([p.visible[] for (p, i) in st.plot_ids if i == id])

    # objects view: each solid has its object shown and its voxels hidden; the loop
    # shows its circle, its edges and arrows only on request
    @test all(id -> visible(id) == [false, true], 1:3)
    @test visible(4) == [false, false, true]

    # hide an object with its checkbox, bring everything back with "Show all"
    boxes[1].checked[] = false
    @test !st.shown[1][] && visible(1) == [false, false]
    st.shown[2][] = false                                    # as by a click
    button("Show all").clicks[] += 1
    @test boxes[1].checked[] && all(id -> st.shown[id][], 1:4)

    # voxel view: the voxels are built, the objects hidden, the loop on its edges
    faces(id) = length(st.voxels[id][].faces)
    view_menu.i_selected[] = 2
    @test st.voxel_mode[]
    @test all(id -> faces(id) > 1, 1:3)                     # more than the empty stand-in
    @test all(id -> visible(id) == [false, true], 1:3)       # now the other one
    @test visible(4) == [false, true, true]                  # circle and edges, no arrows

    # cut along y through the ball: a clip plane, and the voxels rebuilt with a cut face
    full = faces(2)
    boxes[5].checked[] = true
    axis_menu.i_selected[] = 2
    @test slider.range[] == d.nodes_v
    set_close_to!(slider, 0.5)
    @test length(st.planes[]) == 1 && st.planes[][1].normal ≈ Vec3f(0, -1, 0)
    @test 0 < faces(2) < full                                # half a sphere and its cut face
    boxes[6].checked[] = true                                # grid in the cut plane
    boxes[5].checked[] = false
    @test isempty(st.planes[]) && faces(2) == full

    # loop options in the objects view
    view_menu.i_selected[] = 1
    boxes[7].checked[] = true; boxes[8].checked[] = true
    @test visible(4) == [true, true, true]

    # reset view: the same camera as before, after turning it
    cam = Makie.cameracontrols(st.ls.scene)
    state() = (cam.eyeposition[], cam.lookat[], cam.upvector[])
    button("Reset view").clicks[] += 1
    start = state()
    @test normalize(start[1] - start[2]) ≈ normalize(Vec3f(1, 1, 1))   # Makie's default direction
    update_cam!(st.ls.scene, cam, Vec3f(-2, 0.5, 3), Vec3f(0.5), Vec3f(0, 1, 0))
    @test !all(state() .≈ start)
    button("Reset view").clicks[] += 1
    @test all(state() .≈ start)

    # what a click picks is traced back to its object: a plot drawn for it directly,
    # a part of a composite plot (the arrow meshes inside arrows3d), or nothing
    arrows = only(p for (p, i) in st.plot_ids if i == 4 && p isa Makie.Arrows3D)
    @test _VIEW._picked_id(st.plot_ids, arrows) == 4
    @test _VIEW._picked_id(st.plot_ids, first(arrows.plots)) == 4
    @test _VIEW._picked_id(st.plot_ids, nothing) === nothing
    @test _VIEW._picked_id(st.plot_ids, first(p for p in st.ls.scene.plots if p isa Makie.Wireframe)) === nothing

    # a click outside the scene hides nothing
    ev = events(fig).mousebutton
    ev[] = Makie.MouseButtonEvent(Mouse.left, Mouse.press)
    ev[] = Makie.MouseButtonEvent(Mouse.left, Mouse.release)
    ev[] = Makie.MouseButtonEvent(Mouse.right, Mouse.press)
    @test all(id -> st.shown[id][], 1:4)

    # more than 15 objects: one checkbox per type; no objects: just the settings
    m = create_domain([1.0, 1.0, 1.0], [0.05, 0.05, 0.05])
    for k in 1:16
        create_sphere!(m, 0.1 + 0.05k, 0.5, 0.5, 0.05)
    end
    @test count(b -> b isa Checkbox, first(_VIEW._view_figure(m)).content) == 1 + 2
    @test count(b -> b isa Checkbox, first(_VIEW._view_figure(create_domain([1.0, 1.0, 1.0],
                                                                 [0.1, 0.1, 0.1]))).content) == 2
end
