#This file was created by 
#Norman Haussmann (haussmann@uni-wuppertal.de), Chair of Electromagnetic Theory, University of Wuppertal
#Date: 13/01/2026


#Docstring generated by Opus 5.0
"""
    _get_dual_facet_averaged_material(config, materialIndex) -> SparseMatrixCSC
    _get_dual_facet_averaged_material(config, materialIndex, material_u, material_v, material_w)

Build a FIT material matrix: a diagonal matrix with one entry per primal edge,
mapping edge voltages to the fluxes through the corresponding dual facets.

Each entry is the dual facet area attached to that edge, weighted by the material
values of the four cells surrounding it, divided by the primal edge length. The
first form uses `config.material` for all three directions; the second takes the
distribution per direction.

`materialIndex` selects which property is averaged, following the layout of
`config.material`:

| index | property     | absolute value used |
|-------|--------------|---------------------|
| 1     | conductivity | σ                   |
| 2     | permittivity | ε₀ · ε_r            |

Index 3 (permeability) is handled by [`get_reluctivity`](@ref) instead, which
averages along the dual edge rather than over the dual facet.

# Anisotropy

`material_u`, `material_v` and `material_w` are the three *diagonal* components
εᵤᵤ, εᵥᵥ, ε_ww of one material tensor — not three separate materials. Because a
FIT material matrix is diagonal, each entry couples one edge to the single dual
facet orthogonal to it, so only the component along that edge is ever needed.

This restricts the representable materials to those whose principal axes align
with the grid (orthotropic). Off-diagonal components such as ε_uv would couple a
u-directed voltage to a v-facet flux, which requires a non-diagonal material
matrix and is not supported.

Each array must have size `(Nu-1) × (Nv-1) × (Nw-1) × 3`, matching
`config.material`.

# Element type

The result's element type is `promote_type` of the three inputs, so real
distributions give a real matrix and complex ones a complex matrix. Passing
complex arrays makes the assembled system complex symmetric — not Hermitian — so
`cholesky` no longer applies.

# Boundary cells

Cells outside the domain are given zero width, so they contribute no area and
their material value never enters a real edge. An edge lying in a boundary plane
therefore receives the geometrically correct half (face) or quarter (domain
edge) dual facet, consistent with `config.dual_facets_*`. The matrix is valid
for natural and magnetic-wall boundaries, not only when boundary degrees of
freedom are eliminated by projection.

The dead edges in the last plane of each direction (see `get_ghost_indices`)
have no dual facet and receive exactly zero. The matrix is therefore only
positive semidefinite on the full 3Nₚ space: restrict to non-ghost indices, or
use a diagonal pseudo-inverse (1/0 := 0), before inverting or factorising it.

# Examples

```julia
Mε = _get_dual_facet_averaged_material(domain, 2)          # isotropic

εr = copy(domain.material)                                  # uniaxial: εᵤᵤ = 5
εr[:, :, :, 2] .= 5.0
Mε = _get_dual_facet_averaged_material(domain, 2, εr, domain.material, domain.material)
```
"""

function _get_dual_facet_averaged_material(config, materialIndex::Int64, material_u, material_v, material_w)
    Nu, Nv, Nw = config.Nu, config.Nv, config.Nw
    Mu, Mv, Mw = 1, Nu, Nu*Nv
    Np = Nu*Nv*Nw

    for (name, m) in (("material_u", material_u), ("material_v", material_v), ("material_w", material_w))
        size(m) == (Nu-1, Nv-1, Nw-1, 3) || throw(DimensionMismatch("$name must be $((Nu-1,Nv-1,Nw-1,3)), got $(size(m))"))
    end

    materialIndex in (1, 2) || throw(ArgumentError("material index $materialIndex is not defined; permeability is handled by get_reluctivity"))

    S = float(promote_type(eltype(material_u), eltype(material_v), eltype(material_w)))

    # ghost layer so the boundary reads below stay in bounds
    function _extend(m)
        e = zeros(S, Nu+1, Nv+1, Nw+1)
        scale = materialIndex == 2 ? ε₀ : 1.0
        @views e[2:end-1, 2:end-1, 2:end-1] .= scale .* m[:, :, :, materialIndex]
        return e
    end

    mat_u, mat_v, mat_w = _extend(material_u), _extend(material_v), _extend(material_w)

    # divisors: duplicated end widths keep dead edges at 0/Δ instead of 0/0
    Extended_Edge_U = vcat(config.edges_u[1], config.edges_u, config.edges_u[end])
    Extended_Edge_V = vcat(config.edges_v[1], config.edges_v, config.edges_v[end])
    Extended_Edge_W = vcat(config.edges_w[1], config.edges_w, config.edges_w[end])

    # areas: zero-width ghost cells contribute no facet area
    Extended_Edge_U_0 = vcat(0.0, config.edges_u, 0.0)   
    Extended_Edge_V_0 = vcat(0.0, config.edges_v, 0.0)   
    Extended_Edge_W_0 = vcat(0.0, config.edges_w, 0.0)   

    A_u = (Extended_Edge_V_0 .* Extended_Edge_W_0') .* 0.25
    A_v = (Extended_Edge_U_0 .* Extended_Edge_W_0') .* 0.25
    A_w = (Extended_Edge_U_0 .* Extended_Edge_V_0') .* 0.25

    newAveraged = zeros(S, 3*Np)

    @threads for k in 1:Nw
        @inbounds for j in 1:Nv, i in 1:Nu
            p = 1 + (i-1)*Mu + (j-1)*Mv + (k-1)*Mw

            newAveraged[p] = (mat_u[i+1,j+1,k+1]*A_u[j+1,k+1] + mat_u[i+1,j,k+1]*A_u[j,k+1] +
                              mat_u[i+1,j+1,k  ]*A_u[j+1,k  ] + mat_u[i+1,j,k  ]*A_u[j,k  ]) / Extended_Edge_U[i+1]

            newAveraged[p+Np] = (mat_v[i+1,j+1,k+1]*A_v[i+1,k+1] + mat_v[i,j+1,k+1]*A_v[i,k+1] +
                                 mat_v[i+1,j+1,k  ]*A_v[i+1,k  ] + mat_v[i,j+1,k  ]*A_v[i,k  ]) / Extended_Edge_V[j+1]

            newAveraged[p+2Np] = (mat_w[i+1,j+1,k+1]*A_w[i+1,j+1] + mat_w[i,j+1,k+1]*A_w[i,j+1] +
                                  mat_w[i+1,j,k+1]*A_w[i+1,j  ] + mat_w[i,j,k+1]*A_w[i,j  ]) / Extended_Edge_W[k+1]
        end
    end

    return spdiagm(0 => newAveraged)
end

# isotropic default
_get_dual_facet_averaged_material(config, materialIndex::Int64) = _get_dual_facet_averaged_material(config, materialIndex, config.material, config.material, config.material)