#This file was created by 
#Norman Haussmann (haussmann@uni-wuppertal.de), Chair of Electromagnetic Theory, University of Wuppertal
#Date: 13/01/2026


#Docstring generated by Opus 5.0
"""
    _get_dual_facet_averaged_material(config, materialIndex) -> SparseMatrixCSC
    _get_dual_facet_averaged_material(config, materialIndex, material_u, material_v, material_w)

Build a FIT material matrix: a diagonal matrix with one entry per primal edge,
mapping edge voltages to the fluxes through the corresponding dual facets.

Each entry is the dual facet area attached to that edge, weighted by the material
values of the four cells surrounding it, divided by the primal edge length. The
first form uses `config.material` for all three directions; the second takes the
distribution per direction.

`materialIndex` selects which property is averaged, following the layout of
`config.material`:

| index | property     | absolute value used |
|-------|--------------|---------------------|
| 1     | conductivity | σ                   |
| 2     | permittivity | ε₀ · ε_r            |

Index 3 (permeability) is handled by [`get_reluctivity`](@ref) instead, which
averages along the dual edge rather than over the dual facet.

# Anisotropy

`material_u`, `material_v` and `material_w` are the three *diagonal* components
εᵤᵤ, εᵥᵥ, ε_ww of one material tensor — not three separate materials. Because a
FIT material matrix is diagonal, each entry couples one edge to the single dual
facet orthogonal to it, so only the component along that edge is ever needed.

This restricts the representable materials to those whose principal axes align
with the grid (orthotropic). Off-diagonal components such as ε_uv would couple a
u-directed voltage to a v-facet flux, which requires a non-diagonal material
matrix and is not supported.

Each array must have size `(Nu-1) × (Nv-1) × (Nw-1) × 3`, matching
`config.material`.

# Element type

The result's element type is `promote_type` of the three inputs, so real
distributions give a real matrix and complex ones a complex matrix. Passing
complex arrays makes the assembled system complex symmetric — not Hermitian — so
`cholesky` no longer applies.

# Boundary cells

The distributions are padded with one ghost layer carrying the vacuum value
(0 for conductivity, ε₀ for permittivity), which removes the special cases at the
grid faces. A boundary edge therefore receives a full dual facet rather than the
half facet that geometrically exists there, so boundary entries are larger than
the geometry implies. This is harmless when the boundary degrees of freedom are
eliminated by a projection matrix, which is the usual case.

# Examples

```julia
Mε = _get_dual_facet_averaged_material(domain, 2)          # isotropic

εr = copy(domain.material)                                  # uniaxial: εᵤᵤ = 5
εr[:, :, :, 2] .= 5.0
Mε = _get_dual_facet_averaged_material(domain, 2, εr, domain.material, domain.material)
```
"""

function _get_dual_facet_averaged_material(config, materialIndex::Int64, material_u, material_v, material_w)
    Nu, Nv, Nw = config.Nu, config.Nv, config.Nw
    Mu, Mv, Mw = 1, Nu, Nu*Nv
    Np = Nu*Nv*Nw

    for (name, m) in (("material_u", material_u), ("material_v", material_v), ("material_w", material_w))
        size(m) == (Nu-1, Nv-1, Nw-1, 3) || throw(DimensionMismatch("$name must be $((Nu-1,Nv-1,Nw-1,3)), got $(size(m))"))
    end

    defaultFill = materialIndex == 1 ? 0.0 :
                  materialIndex == 2 ? ε₀  :
                  throw(ArgumentError("material index $materialIndex is not defined"))

    # ghost layer so the boundary reads below stay in bounds
    S = promote_type(eltype(material_u), eltype(material_v), eltype(material_w))
    function _extend(m)
        e = fill(S(defaultFill), Nu+1, Nv+1, Nw+1)
        if materialIndex == 1
            @views e[2:end-1, 2:end-1, 2:end-1] .= m[:, :, :, materialIndex]
        else
            @views e[2:end-1, 2:end-1, 2:end-1] .*= m[:, :, :, materialIndex]
        end
        return e
    end

    background = materialIndex == 1 ? 0.0 : 1.0

    function _check_outer_filling(m, name)
        v = @view m[:, :, :, materialIndex]
        touching = any(!=(background), @view(v[1,   :,   :])) || any(!=(background), @view(v[end, :,   :])) ||
                any(!=(background), @view(v[:,   1,   :])) || any(!=(background), @view(v[:, end,   :])) ||
                any(!=(background), @view(v[:,   :,   1])) || any(!=(background), @view(v[:,   :, end]))
        touching && @warn "$name: outermost cells hold non-default material; \
                        they are averaged against vacuum at the boundary" maxlog=1
    end

    _check_outer_filling(material_u, "material_u")
    _check_outer_filling(material_v, "material_v")
    _check_outer_filling(material_w, "material_w")
    mat_u, mat_v, mat_w = _extend(material_u), _extend(material_v), _extend(material_w)

    Extended_Edge_U = vcat(config.edges_u[1], config.edges_u, config.edges_u[end])
    Extended_Edge_V = vcat(config.edges_v[1], config.edges_v, config.edges_v[end])
    Extended_Edge_W = vcat(config.edges_w[1], config.edges_w, config.edges_w[end])

    A_u = (Extended_Edge_V .* Extended_Edge_W') .* 0.25
    A_v = (Extended_Edge_U .* Extended_Edge_W') .* 0.25
    A_w = (Extended_Edge_U .* Extended_Edge_V') .* 0.25

    newAveraged = zeros(S, 3*Np)

    @threads for k in 1:Nw
        @inbounds for j in 1:Nv, i in 1:Nu
            p = 1 + (i-1)*Mu + (j-1)*Mv + (k-1)*Mw

            newAveraged[p] = (mat_u[i+1,j+1,k+1]*A_u[j+1,k+1] + mat_u[i+1,j,k+1]*A_u[j,k+1] +
                              mat_u[i+1,j+1,k  ]*A_u[j+1,k  ] + mat_u[i+1,j,k  ]*A_u[j,k  ]) / Extended_Edge_U[i+1]

            newAveraged[p+Np] = (mat_v[i+1,j+1,k+1]*A_v[i+1,k+1] + mat_v[i,j+1,k+1]*A_v[i,k+1] +
                                 mat_v[i+1,j+1,k  ]*A_v[i+1,k  ] + mat_v[i,j+1,k  ]*A_v[i,k  ]) / Extended_Edge_V[j+1]

            newAveraged[p+2Np] = (mat_w[i+1,j+1,k+1]*A_w[i+1,j+1] + mat_w[i,j+1,k+1]*A_w[i,j+1] +
                                  mat_w[i+1,j,k+1]*A_w[i+1,j  ] + mat_w[i,j,k+1]*A_w[i,j  ]) / Extended_Edge_W[k+1]
        end
    end

    return spdiagm(0 => newAveraged)
end

# isotropic default
_get_dual_facet_averaged_material(config, materialIndex::Int64) = _get_dual_facet_averaged_material(config, materialIndex, config.material, config.material, config.material)